### ISSUE TITLE
Jekyll App Deployment Results in many HTTP 301 Redirects

### ISSUE THREAD

**Issue by mmacfadden** [aws-amplify/amplify-hosting#1265]
**Describe the bug**
I have a Jekyll site that runs perfectly locally. When I try to deploy it with amplify many of the CSS and Javascript files fail to load.  It appears that they are getting redirected with a trailing slash appended, followed by a 403 error.

The web site is deployed here:

https://master.d1rbvrsz7elg3.amplifyapp.com/

**To Reproduce**
1. curl -v https://master.d1rbvrsz7elg3.amplifyapp.com/assets/vendor/venobox/venobox.min.js

**Expected behavior**
The file should be returned with a HTTP 200.

**Screenshots**
```
*   Trying 13.227.41.42...
* TCP_NODELAY set
* Connected to master.d1rbvrsz7elg3.amplifyapp.com (13.227.41.42) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.d1rbvrsz7elg3.amplifyapp.com
*  start date: Nov 21 00:00:00 2020 GMT
*  expire date: Dec 20 23:59:59 2021 GMT
*  subjectAltName: host "master.d1rbvrsz7elg3.amplifyapp.com" matched cert's "*.d1rbvrsz7elg3.amplifyapp.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fcc1f009200)
> GET /assets/vendor/venobox/venobox.min.js HTTP/2
> Host: master.d1rbvrsz7elg3.amplifyapp.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 301 
< content-type: application/xml
< content-length: 0
< date: Sun, 22 Nov 2020 00:13:25 GMT
< server: AmazonS3
< location: /assets/vendor/venobox/venobox.min.js/
< x-cache: Miss from cloudfront
< via: 1.1 2cf721793a9b30d4a9da8af07ca04883.cloudfront.net (CloudFront)
< x-amz-cf-pop: MSP50-C1
< x-amz-cf-id: 4hRVzRZYp3KVgoiW3teOqAKc2NQG_JXKX20s5_QjkZkq4Ia-AYjzyQ==
< 
* Connection #0 to host master.d1rbvrsz7elg3.amplifyapp.com left intact
* Closing connection 0
```

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser Chrome
 - Version 87

**Additional context**
If there was a way to see what the deployed file structure looked like perhaps I could debug the issue.  The site seems to build and get deployed. It's possible that in the build agent that some files are not getting built or deployed. But I can't figure out how to debug this.

**Comment by mmacfadden** [comment]
In case you need it:

**Region**: us-east-2
**API Id**: d1rbvrsz7elg3

**Comment by dchura** [comment]
I have the very same curl output as you.  In my case, I have two URLs that are identical except for a filename, and one fails and one succeeds.  It seems possible that the amplify code to add trailing slashes could be error prone, as it appears to be a hueristic to solve some problem (though I don't know what problem it does solve).   Seems there's no way to shut off the automatically-add-slashes feature.

**Comment by mmacfadden** [comment]
Yep. And some files work fine.. and others don't work at all.  I can't figure out the pattern.

**Comment by dchura** [comment]
Right - that's why I'm considering re-naming my files.  However, the react.js compiler mangles all filenames so I can't control the exact names used

**Comment by dchura** [comment]
To be perfectly honest, I'm not sure I'm reported the error in the right place.  There's a bunch of amplify projects

**Comment by dchura** [comment]
Not sure if you saw a comment I made in my bug report.  I created a new Amplify app from scratch, populated it with the identical web-app build (that was failing) and it had no redirect issues.  It also worked after I added the SPA redirect (which I feared was the issue). The only thing I haven't done is move to my custom domain name for that app.

Of note is that the file names in the new app are identical to what they were in the failing app, so that makes it a bit more complicated.

You might try creating another app from scratch as see what happens.

**Comment by mmacfadden** [comment]
I'll give it a shot

**Comment by mmacfadden** [comment]
Tried re-deploying a new app. Unfortunately. I had had the same result. :-(

**Comment by dchura** [comment]
Dang.  I think I just got lucky then, though I’m now suspicious of how long it might last….

Dave Chura
Founder
[A picture containing shape  Description automatically generated]
www.enclayvegroup.com<http://www.enclayvegroup.com>

**Comment by dchura** [comment]
Well I was right.  I’ve updated my app several times and now it fails just as it did before.  And the files that fail have identical names and paths as when they worked.

This all makes me think Amplify just isn’t ready for a production system.   I hope someone from Amplify sees this.

Dave Chura
Founder
[A picture containing shape  Description automatically generated]
www.enclayvegroup.com<http://www.enclayvegroup.com>


From: David Chura <dave@enclayve.com>
Date: Tuesday, November 24, 2020 at 9:51 AM
To: aws-amplify/amplify-console <reply@reply.github.com>, aws-amplify/amplify-console <amplify-console@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: Re: [aws-amplify/amplify-console] Jekyll App Deployment Results in many HTTP 301 Redirects (#1265)

Dang.  I think I just got lucky then, though I’m now suspicious of how long it might last….

Dave Chura
Founder
[A picture containing shape  Description automatically generated]
www.enclayvegroup.com<http://www.enclayvegroup.com>

**Comment by mmacfadden** [comment]
FYI.. I used the manual deploy method to just deploy the built folder by dragging it to the browser. That deployed just fine and works with no problem.  I am starting to think the the build / deploy step might not be copying over all the files consistently.

Is it possible that sometimes some of the files are not being copied / deployed. Resulting in the "clean url" mechanism kicking in and trying to append a slash?

**Comment by mmacfadden** [comment]
For reference, here is the manual deploy version.

https://test.d379gtxws90n8j.amplifyapp.com/

**Comment by dchura** [comment]
I have been using the manual deploy method as well – just dragging the build folder over.   And yes, it worked perfectly the first time in each of my apps. I’m not sure if it failed the very next time I dragged the folder to amplify but after 3 or 4 times it was broken.

I think you are on to something as to which files might not be copied correctly.  I haven’t used the amplify cli, but I did install it.  I think there was a “clean” function in the CLI  so maybe that’s the solution – to manually do a clean (if it is there at all…).   I think I’ll follow that thread..

Thanks Michael

Dave Chura
Founder
[A picture containing shape  Description automatically generated]
www.enclayvegroup.com<http://www.enclayvegroup.com>

**Comment by mmacfadden** [comment]
I am not sure if this is the issue but I see this in the logs:

```
2020-11-25T15:18:04.155Z [INFO]: # Starting build artifact upload process...
2020-11-25T15:18:04.723Z [INFO]: # Build artifact is: 8MB
2020-11-25T15:18:04.751Z [INFO]: # Build artifact is: 8MB
2020-11-25T15:18:04.752Z [INFO]: # Uploading build artifact '__artifacts.zip'...
2020-11-25T15:18:04.797Z [INFO]: # Uploading build artifact '__artifactsHash.zip'...
```

When I zip the _site directory myself it is more like 11MB.  Then in the deploy phase I see this:

```
2020-11-25T15:18:09 [INFO]: Beginning deployment for application d1rbvrsz7elg3, branch:master, buildId 0000000008
2020-11-25T15:18:09 [INFO]: Got archive: 7806624 bytes
2020-11-25T15:18:09 [INFO]: Archive unzipped: 53 files
2020-11-25T15:18:10 [INFO]: Deployment complete
```

Note the 53 files...  When I look at my local machine and do the following:

```
 find _site -type f | wc -l
     120
```

It looks like many of the files are not being zipped up into the archive for deployment.

**Comment by dchura** [comment]
Interesting – maybe I should try to zip the directory and drag that over, versus just dragging the folder itself.  I wouldn’t be surprised if Amplify tried to do something “smart” like trying to figure out what files had changed when you just drag the folder

BTW, I didn’t find a “clean” in the CLI as I thought would be there… haven’t spent much time though

Dave Chura
Founder
[A picture containing shape  Description automatically generated]
www.enclayvegroup.com<http://www.enclayvegroup.com>

**Comment by dchura** [comment]
Michael – this is unbelievable.

I zipped my build directory to get build.zip on my laptop (a mac).  In the Amplify console, I dragged and dropped that zip file instead of the directory itself.

And it fixed the redirect problems!  This is the first time I used the zip file method, as I’ve always just dragged the folder.

It’s breaking news, so needs to be repeated and stand the test of time before I’ll move our production work to Ampllify

Dave Chura
Founder
[A picture containing shape  Description automatically generated]
www.enclayvegroup.com<http://www.enclayvegroup.com>


From: David Chura <dave@enclayve.com>
Date: Wednesday, November 25, 2020 at 8:43 AM
To: aws-amplify/amplify-console <reply@reply.github.com>, aws-amplify/amplify-console <amplify-console@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: Re: [aws-amplify/amplify-console] Jekyll App Deployment Results in many HTTP 301 Redirects (#1265)

Interesting – maybe I should try to zip the directory and drag that over, versus just dragging the folder itself.  I wouldn’t be surprised if Amplify tried to do something “smart” like trying to figure out what files had changed when you just drag the folder

BTW, I didn’t find a “clean” in the CLI as I thought would be there… haven’t spent much time though

Dave Chura
Founder
[A picture containing shape  Description automatically generated]
www.enclayvegroup.com<http://www.enclayvegroup.com>

**Comment by dchura** [comment]
Well – it didn’t take long to break it again.  The very next publish failed where a set of static image files had bad redirects.

I have deployed the app several times using the same zip file and then using the same folder, all without any changes in between.  It’s a mess – sometimes everything gets fixed, then sometimes some files work and some don’t, then a different set breaks.

The Amplify CLI has a “delete” and a “publish”. – I might try switching to the CLI and always do a delete before publish.  I’m just not sure what is deleted – don’t want my custom domain and rewrites deleted…

Anyway…

Dave Chura
Founder
[A picture containing shape  Description automatically generated]
www.enclayvegroup.com<http://www.enclayvegroup.com>


From: David Chura <dave@enclayve.com>
Date: Wednesday, November 25, 2020 at 7:14 PM
To: aws-amplify/amplify-console <reply@reply.github.com>, aws-amplify/amplify-console <amplify-console@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: Re: [aws-amplify/amplify-console] Jekyll App Deployment Results in many HTTP 301 Redirects (#1265)

Michael – this is unbelievable.

I zipped my build directory to get build.zip on my laptop (a mac).  In the Amplify console, I dragged and dropped that zip file instead of the directory itself.

And it fixed the redirect problems!  This is the first time I used the zip file method, as I’ve always just dragged the folder.

It’s breaking news, so needs to be repeated and stand the test of time before I’ll move our production work to Ampllify

Dave Chura
Founder
[A picture containing shape  Description automatically generated]
www.enclayvegroup.com<http://www.enclayvegroup.com>


From: David Chura <dave@enclayve.com>
Date: Wednesday, November 25, 2020 at 8:43 AM
To: aws-amplify/amplify-console <reply@reply.github.com>, aws-amplify/amplify-console <amplify-console@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: Re: [aws-amplify/amplify-console] Jekyll App Deployment Results in many HTTP 301 Redirects (#1265)

Interesting – maybe I should try to zip the directory and drag that over, versus just dragging the folder itself.  I wouldn’t be surprised if Amplify tried to do something “smart” like trying to figure out what files had changed when you just drag the folder

BTW, I didn’t find a “clean” in the CLI as I thought would be there… haven’t spent much time though

Dave Chura
Founder
[A picture containing shape  Description automatically generated]
www.enclayvegroup.com<http://www.enclayvegroup.com>

**Comment by dangreenisrael** [comment]
This is impacting us as well

**Comment by dchura** [comment]
Take a look at some of my comments and my own reported issue, which is essentially the same but fails for static image files.

In short, I found the Amplify behavior to be unpredictable – that is, repeated publishing of the exact same build directory (or exact same build.zip) results in different behavior. That is, sometimes everything works, then some image files fail, then other image files fail.  If you could consider this a workaround – just keep publishing the same thing over and over again until it works. I’m just kidding – there’s something wrong here

I haven’t tried it yet, but I’m considering using the Amplify CLI and always do a delete of the app, following by a publish.  Maybe that will have predictable behavior

Dave Chura
Founder
[A picture containing shape  Description automatically generated]
www.enclayvegroup.com<http://www.enclayvegroup.com>

**Comment by Tarun-S** [comment]
I wonder why this began happening only recently. Must've been due to an update on Amplify's side.

**Comment by walkingriver** [comment]
Well, I tried the trick of zipping up my `dist` folder (it's an Angular app) and uploading that. Now the app seems to work. I zipped the contents of `dist` and not the folder itself. All the files appear to be loading properly.

**Comment by dchura** [comment]
Not to rain on the parade…. But I found that the zip workaround sometimes also failed.  Seems repeated attempts or alternating attempts with the zip file and not zip file eventually work, but there’s regression testing required to make sure everything works (and nothing new is broken).

I’ve essentially gone in another direction from amplify for now.  We use it for a test bed, not for production.

I had hoped that someone related to the amplify product would weigh in.

Dave Chura
Founder
[A picture containing shape  Description automatically generated]
www.enclayvegroup.com<http://www.enclayvegroup.com>

**Comment by walkingriver** [comment]
I think you're onto something, Dave. Fortunately, we are only using Amplify for proof-of-concept and testing. I don't think I'd host a production app here at this point. Thanks for the follow-up.

**Comment by Evellior** [comment]
I noticed your comments on #1266, and it sounds very similar, but I wouldn't expect curl to cache the response.  

According to [this thread](https://serverfault.com/questions/698077/does-curl-cache-requests), it could be the response server caching the 301.  If that's the case, there's a header you should be able to include in your curl (`"Cache-Control: no-cache"`) to see if that's the case.

If that is the case though, I'm not sure how you get the response server to flush its cache..

**Comment by saadataz** [comment]
The issue is no longer reproducible. 

Amplify only appends / to a URL for HTML pages to implement the Clean URL feature
https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#trailing-slashes-and-clean-urls
