### ISSUE TITLE
user-agent header in request getting replaced by "Amazon Cloudfront"

### ISSUE THREAD

**Issue by vinay-aryan** [aws-amplify/amplify-hosting#1992]
my application is not receiving actual user-agent value of customer device it's getting replace by  "Amazon Cloudfront". we don't have any setting that can change this cloudfront configuration

**Comment by p00000001** [comment]
I'm also experiencing this problem. My Next.js app in AWS Amplify uses the `user-agent` header but it's always "Amazon Cloudfront". Each page is dynamic so doesn't require caching.

I see this issue is over 2 years old. Is there now a way can we this off or somehow access the Cloudfront configuration for our AWS Amplify apps?

**Comment by p00000001** [comment]
@Jay2113 - could you advise if there is any current solution to this issue or plans to fix it? As it's preventing us from deploying our app on AWS. Many thanks.

**Comment by p00000001** [comment]
@vinay-aryan Were you ever able to find a solution to this issue? Thanks!

**Comment by kaito-hao** [comment]
Hello Amplify team, good to see this is in progress. Could you please kindly provide an ETA? We are rolling out a feature blocked by this. Thank you.

**Comment by mauerbac** [comment]
This feature is now supported with our latest launch!

Check out the details here: https://aws.amazon.com/blogs/mobile/cdn-caching-improvements-for-better-app-performance-with-aws-amplify-hosting/
