### ISSUE TITLE
Admin UI Sign In problem

### ISSUE THREAD

**Issue by otabek1** [aws-amplify/amplify-hosting#2420]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dvv8mgxnlvujd

### Region

ap-south-1

### Environment name

staging

### Amplify CLI Version

6.0.0

### What operating system are you using?

Mac

### Browser type?

Google Chrome

### Describe the bug

I had no trouble accessing admin UI before. First, I tried to add team members from the console then it gave **unable to create user** error message. Then I added an IAM user with full access. Then, neither I nor the IAM user could access admin UI. It kept asking for a username and password. It tried with my password but did not work. Even when I am signed in as a root admin, it is still asking for a password. I tried through CLI as well.  Deleting IAM uses also did not help. The app is not newly created.
Screenshots:

<img width="1429" alt="Screen Shot 2021-11-26 at 5 25 30 PM" src="https://user-images.githubusercontent.com/58929067/143658909-86a0c86c-6723-4a67-97a2-4990f942105b.png">
<img width="1436" alt="Screen Shot 2021-11-26 at 5 28 27 PM" src="https://user-images.githubusercontent.com/58929067/143658985-40e142fc-f4fc-4003-8b32-55820779fd96.png">

### Expected behavior

It should have not asked for username and password for accessing admin UI from console when signed in as root user.

### Reproduction steps

1. Create an amplify project
2. Add IAM users with full access.
2. Try accessing Admin UI

**Comment by Jay2113** [comment]
Hi @otabek1 👋 , thanks for your continued patience and we sincerely apologize for the delayed response on this thread.

It looks like you have deleted the Amplify app `dvv8mgxnlvujd` and thus we won't be able to review its configuration details from our end to troubleshoot and debug this behavior. That being said, we have made significant improvements to the Amplify CLI, Amplify Studio (formerly known as Admin UI) and Amplify Hosting in the past couple of years from when the issue was raised.

I am going to close this thread but please feel free to open a new GitHub issue using our [bug template](https://github.com/aws-amplify/amplify-hosting/issues/new?assignees=&labels=pending-triage&projects=&template=1.bug_report.yaml) if you are still experiencing this behavior.

Thank you!
