### ISSUE TITLE
HTTP request doesn't work when i add my custom dns

### ISSUE THREAD

**Issue by PaulRbl** [aws-amplify/amplify-hosting#2628]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1uy9y2qh9qfmm

### Region

eu-west-3

### Amplify Console feature

Redirects

### Describe the bug

My HTTP request works on the original app but not when i add the custom dns 

### Expected behavior

HTTP requests should work well in both cases as it did before

### Reproduction steps

1. I saw the app wasn't working anymore
2. I tried looking the original app and it was working
3. Only when i have the custom dns the http request bug so i guess it is because of the redirect but i don't know how to fix it

**Comment by hloriana** [comment]
Hi @PaulRbl 👋🏽 thanks for opening this issue. Is there a specific error you run into when accessing your website? Can you provide screenshots of what you see?

**Comment by PaulRbl** [comment]
Hello @hloriana , 
I have this error : "Access to XMLHttpRequest at 'https://api.metaplex.solana.com/' from origin 'https://www.fluxers-official.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status."
![image](https://user-images.githubusercontent.com/83174709/157390152-a9d8b157-5150-4c5c-9e2f-6def6926a084.png)

**Comment by calavera** [comment]
Hi @PaulRbl. The reason why it doesn't work is because api.metaplex.solana.com doesn't allow certain type of requests based on their CORS policy.

Make sure the CORS policy for api.metaplex.solana.com allow requests from your new domain. You can read more about CORS headers in these two articles:

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

This is usually a missconfiguration between the code in the client website and the backend receiving POST requests. We cannot do much about it unfortunately.

Let us know if the problem persists after verifying that the right CORS configuration is in place, and we can take a second look at it.
