### ISSUE TITLE
 This main.d2hym6fc5ycmqc.amplifyapp.com page can’t be foundNo webpage was found for the web address: https://main.d2hym6fc5ycmqc.amplifyapp.com/ HTTP ERROR 404

### ISSUE THREAD

**Issue by lucasvexed** [aws-amplify/amplify-hosting#2778]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2hym6fc5ycmqc

### Region

us-east-1

### Step

Domain Activation

### Status

Failed

### Issue or question

I can't get access to my app web page after the deployement in aws amplify.

### Error message

 This main.d2hym6fc5ycmqc.amplifyapp.com page can’t be foundNo webpage was found for the web address: https://main.d2hym6fc5ycmqc.amplifyapp.com/ HTTP ERROR 404.

**Comment by hloriana** [comment]
Hey @lucasvexed it looks like the `baseDirectory` has not been set in your build scripts. Because of this, Amplify cannot detect the `index.html` file. Amplify will automatically detect the appropriate build settings based on the framework used. Please modify your build script (you can access this under **build settings**) according to this documentation: https://docs.aws.amazon.com/amplify/latest/userguide/getting-started.html#step-2a-confirm-build-settings-for-the-front-end
