### ISSUE TITLE
The Lambda function associated with the CloudFront distribution was throttled for static site

### ISSUE THREAD

**Issue by akasummer** [aws-amplify/amplify-hosting#2889]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1lo8ld0j0d7ve

### Region

eu-central-1

### Amplify Hosting feature

Not applicable

### Describe the bug

We are hosting a static site on Amplify (SSG using Nuxt framework). 99% of time it's working fine, however 1-2 times a day we get a spike of 503 errors (usually it's 0):

```
503 ERROR
The request could not be satisfied.
The Lambda function associated with the CloudFront distribution was throttled. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
```
This is how 5xx error metrics look like:
![Screenshot 2022-07-27 at 17 29 44](https://user-images.githubusercontent.com/11457918/181287772-0e257a59-2c93-4688-82c7-1a019b599ebf.png)

### Expected behavior

Expect to not have any 5xx errors from CloudFront.

### Reproduction steps

Unfortunately, we can't reproduce it. No deploys were done, no changes. 5xx errors appear out of the blue. Could be related to higher traffic volume, but in this case we would like to know how to scale the capacity?

**Comment by Jay2113** [comment]
On 7/25, we experienced increased errors rates in eu-central-1. The issue has been resolved and the service is operating normally.

Additionally, please note that whenever we have customer impact due to issues like this, we post updates to your Personal Health Dashboard (PHD): https://aws.amazon.com/premiumsupport/technology/aws-health-dashboard/

If you experience such issues in the future and if you do not observe any related PHD posts in your account please open a new issue with us and we can investigate into it further.
