### ISSUE TITLE
Unable to link custom domain

### ISSUE THREAD

**Issue by ilyabezdelev** [aws-amplify/amplify-hosting#2975]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d16g4nud7fvld1

### Region

us-east-2

### Step

SSL Creation

### Status

Failed

### Issue or question

I had my blog and podcast's site hosted on it for years and all of a sudden today the cert expired and Chrome/Safari show warnings. It looks like [other people](https://github.com/aws-amplify/amplify-hosting/issues/996) had similar issues and the path forward is to remove the domain and add it again.

I removed the domain but now Amplify can't provision a certificate at all with no clear path forward. The suggested next step is to open a support case but I don't have an AWS support subscription to do so.

There are two issues: 1) cert expiration with no warning, 2) inability to provision a new domain at all for an existing app.

![image](https://user-images.githubusercontent.com/5742823/188927893-fb57a290-ad2a-4a1b-9b19-0c1cb0a961ae.png)

**Comment by Jay2113** [comment]
Thanks for raising this issue with us @ilyabezdelev.

**General Process:**
- Amplify issues an SSL/TLS certificate for all domains connected to your app so that all traffic is secured through HTTPS/2.
- The certificate generated by AWS Certificate Manager (ACM) is valid for 13 months and renews automatically as long as your app is hosted with Amplify.
- Amplify can't renew the certificate if the CNAME verification record has been modified or deleted in the DNS settings with your domain provider. You must then delete and add the domain again in the Amplify console.

**Current Scenario:**
- After doing a deep dive on the issue internally with the ACM service team, we were able to identify the root cause and its as follows:
- Amazon relies on a third party as part of our process for issuing and renewing certificates issued by Amazon Trust Services. As of March 10, 2022, and until further notice, due to changes implemented by that third party to disallow the issuance and renewal of certificates from the domains specified later, we will no longer be able to issue or renew certificates from the domains specified through ACM. All Amazon certificates for these domains will remain functional until expiration, but will not be renewable and no new certificates from these domains will be issued:
```
.RU
.BY
Бел - Belarus
Рф - Russian Federation
.moscow
.москва - Moscow
.SU - Soviet Union
(http://ru.com/) .RU.COM
.РУС
.RU.NET
```
