### ISSUE TITLE
React Native Expo

### ISSUE THREAD

**Issue by bully82** [aws-amplify/amplify-hosting#2978]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-west-2:258208292471:apps/d1aahrptmxeih7

### Region

eu-west 2

### Environment name

staging

### If applicable, what version of Node.js are you using?

v16.17.0

### What operating system are you using?

Windows

### Browser type?

Chrome

### Describe the bug

Im trying to host a react native app using expo. It fails on the build of front end every time

### Expected behavior

Would expect the build to complete it fails on Front End Step. 

### Reproduction steps

Click hosting environments
Git Hub
Connect the required branch/repo
Buil runs and fails on front end step

**Comment by letsbelopez** [comment]
Transferring to hosting because customer is having issues deploying app to hosting

**Comment by Jay2113** [comment]
Hi @bully82 👋 , thanks for your continued patience and we apologize for the delayed response on this thread.

It seems that the Amplify app `d1aahrptmxeih7` has been deleted and thus we won't be able to review the build logs for it from our end. From the provided [build logs](https://github.com/aws-amplify/amplify-hosting/issues/2978#issuecomment-1241100299) it seems that the build failed due to Node.js version `10.16.0` not being supported by the expo-cli.

That being said, we have made some improvements to the default Amplify Hosting compute container which is used to build Amplify apps and it should now use Node.js version `16.19.0` by default. Additionally, you can also leverage the [live package update](https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates) feature which will enable you to specify versions of packages and dependencies to use by the default compute container.

I am going to close this thread but please feel free to open a new GitHub issue using our [bug template](https://github.com/aws-amplify/amplify-hosting/issues/new?assignees=&labels=pending-triage&projects=&template=1.bug_report.yaml) if you are still experiencing this behavior.

Thank you!
