### ISSUE TITLE
Unable to preview React App in AWS Console

### ISSUE THREAD

**Issue by Flashxjordan** [aws-amplify/amplify-hosting#2993]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d21im8iownpu8j

### Region

us-east-2

### Amplify Hosting feature

Previews

### Describe the bug

I have an app that is connected to my Github repo for deployment. When I start this program from my visual studios, it works perfect. I am able to see my react app start up. However, I get an error message when I click the preview from my AWS Console. 

Truthfully, I am new to github and AWS Amplify so it more than likely is something that I did during the setup process, but I am unable to pinpoint exactly where I messed up.

### Expected behavior

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>

### Reproduction steps

I followed the installation steps from this link [](https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-one/?e=gs2020&p=build-a-react-app-intro)

### Additional information

I wish I could explain more in-depth. Still trying to learn my way around these resources. Thanks

**Comment by hloriana** [comment]
Hi @Flashxjordan 👋🏽 thanks for reaching out for assistance! You provided us your account ID but it looks like you have quite a few applications and I wasn't able to determine which application was throwing the `Access Denied` error. Please respond with your App ID so we can assist you. To find your App ID please follow these steps:

1. In the Amplify console, navigate to **App settings** -> **General**
2. Under **App details** you'll see the App ARN. The app ID is the last segment starting with the `d`:
`arn:aws:amplify:ca-central-1:12345678910:apps/d123456abcdef`

As for the `Access Denied` issue, you might have incorrectly set the `baseDirectory` for your React app. Make sure you have `baseDirectory: build` set in your build settings otherwise the Access Denied error can occur. You can read more about this error in our FAQs: https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#access-denied-for-certain-routes-even-with-spa-redirect-rule

**Comment by hloriana** [comment]
Hi @Flashxjordan please disregard my previous message, I was mixing up two different GitHub issues by accident. My apologies! I tried to investigate with your App ID however it appears you have deleted the app. As for the `Access Denied` issue, you might have incorrectly set the `baseDirectory` for your React app. Make sure you have `baseDirectory: build` set in your build settings otherwise the Access Denied error can occur. You can read more about this error in our FAQs: https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#access-denied-for-certain-routes-even-with-spa-redirect-rule
