### ISSUE TITLE
Uploading new files to Amplify site stuck in "Retrieving deployment details"

### ISSUE THREAD

**Issue by dbredthauer** [aws-amplify/amplify-hosting#3004]
We have a very simply site with two files--an index file and a png file. 

Zipped the up and added them manually. Worked great for about 2 weeks. Now it tanks every time I tried to load the zip file.

I've seen others on the support threads  say there is a way to delete the pending upload manually, but I have been unable to figure out how. Any guidance would be appreciated.

**Comment by hloriana** [comment]
Hi @dbredthauer 👋🏽 thanks for reaching out with this issue. Can you please provide a screenshot of what you see when you try to upload the zip file? Also, please check the developer tools for any errors that could help us identify the source of the issue.

If your deployment is stuck in a pending state, please follow these steps for a workaround:
1. Find the ID of the job that is stuck in pending. You can run `aws amplify list-jobs --app-id <value> --branch-name <value>`. This will return JSON with metadata for all the jobs ran for that environment including `jobId` and `status`. Find the job stuck in pending status. ([docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/amplify/list-jobs.html))
2. Stop the pending job by running `aws amplify stop-job --app-id <value> --branch-name <value> --job-id <value>` ([docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/amplify/stop-job.html))

If you are continuing to experience this behavior, please provide us your App ID and any screenshots of errors so that we can root cause this issue. Thank you!

**Comment by hloriana** [comment]
Closing this issue due to no response. Please create a new issue if you continue to experience this behavior. Thank You!
