### ISSUE TITLE
Getting 503 error on some image using next/image and aws s3 with hostend on amplify?

### ISSUE THREAD

**Issue by siamahnaf198** [aws-amplify/amplify-hosting#3013]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3u6pd4nl9nakc

### Region

ap-southeast-1

### Describe the bug

I am facing one problem when I am host my project to `aws amplify`. I successfully build a demo ecommerce project. I deploy this next js project to aws amplify. I use `next/image` component on my project. When I enter my site, I can see some images(Not all image) are not loaded properly. They show alt text instead. You can see this `gif` for understanding.

-https://media.giphy.com/media/bOekkFQdH2OVcoumwj/giphy.gif

You can see live url also- https://www.nekmart.com/

Please see the `gif` for understanding actual problem.

Here I host my image to aws S3. I use cloudfront also. For debugging my problem. I also deploy my project to vercel and netlify. From vercel and netlify I am not getting any kind image not loading issue.Here is those links-

Vercel link- https://nekmart-k71c.vercel.app/ 
Netlify link- https://remarkable-licorice-795c08.netlify.app/

But I have to use aws. Now How can I debug my problem? I can't understand actually where is the problem occured-

1. `next/image` component problem- I use it in this way- `<Image src={process.env.NEXT_PUBLIC_IMAGE_PATH + brand.image} width={25} height={25} alt={brand.name} />`
3. Need to setting up `aws amplify` properly?
5. Need to setting up `aws s3` properly.
6.  Need to setting up `next config` for image component.

I am confused, Which one? Please help me to debugging this problem.

### Expected behavior

Here It need to load image properly.

### Reproduction steps

Form vercel and netlify-

Vercel link- https://nekmart-k71c.vercel.app/ 
Netlify link- https://remarkable-licorice-795c08.netlify.app/

**Comment by hloriana** [comment]
Hi @siamahnaf198 👋🏽 thanks for raising this issue and providing details. 

1. If the source of your image is an external domain then you will need to configure them in your `next.config.js` file otherwise the images will not load. Please see their documentation for more details: [Next/image Domains](https://nextjs.org/docs/api-reference/next/image#domains). Here is an example of how you would add this to your `next.config.js`:

```
module.exports = {
  images: {
    domains: ['assets.acme.com'],
  },
}
```
Please let us know if this does not solve the issue. 

2. If you're new to hosting a Next.js app on AWS Amplify then it would be a great starting point to follow our  documentation: [Deploy a Next.js SSR app with Amplify ](https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app).
3. How do you intend to use AWS S3? If you are using it for storage with your Next.js app, you can get started with that feature by following this guide: [Storage with Amplify](https://docs.amplify.aws/lib/storage/getting-started/q/platform/js/).
4. For guidance on how to configure your `next.config.js` file for using `next/image`, it is best to follow their documentation and examples. [Next/image](https://nextjs.org/docs/api-reference/next/image).

**Comment by siamahnaf198** [comment]
Actually, I create this issue 3 days ago. But I had to show my project to my boss immediately in 2 days. When I was not finding any solution, I had to go other hosting company. Because this is big issue with aws amplify. That’s why I deploy my project to Microsoft azure. You are seeing the project hosted on azure, that's why you are not getting any image not loading issue.

**Comment by hloriana** [comment]
Hi @siamahnaf198 thanks for getting back to us with an update. If you have any other questions regarding hosting SSR apps on AWS Amplify feel free to create a new issue. Thank you!
