### ISSUE TITLE
Possible to change the stack an amplify app points to?

### ISSUE THREAD

**Issue by SaileshKumar** [aws-amplify/amplify-hosting#3058]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2b0b5v0fml6hp

### AWS Region

us-east-2

### Amplify Hosting feature

Backend builds

### Describe the bug

Hi team, 

We had an issue where a team member accidentally ran

`aws amplify delete-app --app-id d2043y24tqcg54 --region us-east-2`

Deleting our production app. This **did not** delete the CloudFormation stack, or any of the corresponding services (our tables, userpool, S3 bucket, etc.). However, it **did** delete the hosting environment. 

To bring the site back online, we created a new amplify app, and manually changed the stack IDs in team-provider-info and hosted it with amplify publish.

Later, we tried to swap it from manual hosting to CI/CD, but then realized that in Amplify backend the app is tied to the stack it was created with, not the stack we tried to change it to. So CI/CD is running on the "wrong" stack, and then fails.

Is it possible to, in the backend, actually update the stack the amplify app is associated with to go back to our original setup? Or do we have to migrate all the table data, S3 data, userpool etc to a new app?

Original amplify app: d2043y24tqcg54
APp that failed to add CI/CD because of the stack discrepancy: d22dhfz89ouuqv
Current Amplify App: d2b0b5v0fml6hp

### Expected behavior

Ideally we can just swap the amplify stack in our current app to enable CI/CD and have it be in a proper state.

### Reproduction steps

I'm not sure if the stack not getting deleted was a bug, or how the command aws amplify delete-app works. Assuming it worked as intended:

1. Set up amplify app with data
2. Run aws amplify delete-app
3. Create new app, and now attempt to get it to point to the original stack

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by SaileshKumar** [comment]
@siegerts per discussion from Office Hours, tagging you here. Let me know if any other information would help.

AWS Support Case ID: 11075120001

**Comment by hloriana** [comment]
Hi @SaileshKumar we are currently investigating if changing the CloudFormation template for an Amplify app is possible. I will update you shortly.

**Comment by hloriana** [comment]
@SaileshKumar The `team-provider-info.json` is created to share information about the Amplify app across your team and does not support manual updates which is why changing the stack ID did not help. Please see here for more info: https://docs.amplify.aws/cli/reference/files/#team-provider-infojson

Changing CloudFormation templates is not supported however there is an advanced workflow you can try to potentially work around this issue:

You can export your Amplify project as a Cloud Development Kit (CDK) stack and import the stack into a CDK. Here is the guide for this workflow: [Use an exported Amplify backend in AWS Cloud Development Kit (CDK)](https://docs.amplify.aws/cli/usage/export-to-cdk/#use-an-exported-amplify-backend-in-aws-cloud-development-kit-cdk)
