### ISSUE TITLE
Publish/Deploy previous build

### ISSUE THREAD

**Issue by talebbits** [aws-amplify/amplify-hosting#307]
**Is your feature request related to a problem? Please describe.**
We do not have any way to just publish previous build, we have option to `Redeploy this version` what re run all the step it would run if we kick new build like Provision|Build|Deploy|Verify

**Describe the solution you'd like**
It would be ideal if it only run `Deploy|Verify` steps when we `Redeploy this version`

**Comment by fnavarrodev** [comment]
I can not even see the `Redeploy this version` option. Does still exist? The true is that rollbacks are becoming a nightmare using Amplify

**Comment by hyei** [comment]
I see the button, but haven't used it. I had assumed redeploy was using the previous artifact rather than pulling it from the branch and rebuilding from scratch, and was using a manual trigger instead. If redeploy version doesn't work this way, i think it needs to be renamed to "Redeploy this branch".

**Comment by mauerbac** [comment]
We do not have an instant rollback feature but we do have a redeploy previous version. We have a feature request open for instant rollback. Will close this
