### ISSUE TITLE
 Initialize GitHub repository section from Module 1: Deploy and Host a React App

### ISSUE THREAD

**Issue by ghost** [aws-amplify/amplify-hosting#3100]
In Initialize GitHub repository Module 1 section (link: https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-one/?e=gs2020&p=build-a-react-app-intro)

After writing the following line in Git or Node.js command prompt by entering: 
git add . 

I got the following the issue in both Git and Node.js command prompt:

warning: could not open directory 'AppData/Local/Application Data/': Permission denied

Because I am unable to resolve the above warning message issue, I am unable to proceed and complete steps b. and c. of Module 1 tutorial exercise.

Could you please tell me how to resolve it asap?

Thanks so much for your help :)

**Comment by Jay2113** [comment]
This issue seems to be occurring because they are trying to perform git operations in an incorrect directory: https://stackoverflow.com/questions/50823420/git-add-filename-not-working.

Closing this thread since its unrelated to Amplify Hosting and [documentation](https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-one/?e=gs2020&p=build-a-react-app-intro) is up to date too.
