### ISSUE TITLE
Fix support for node 18

### ISSUE THREAD

**Issue by hhemmati81** [aws-amplify/amplify-hosting#3109]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d656n35c0hsyb

### AWS Region

us-west-2

### Amplify Hosting feature

Deployments

### Describe the bug

Setting the node version to 18 in the build settings fails deployments with the following error message. Node 18 is the minimum requirement for Gatsby 5.

`2022-11-15T19:19:02.924Z [WARNING]: node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)
                                    node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by node)`

### Expected behavior

It should be able to build using the latest LTS version of the node which is 18

### Reproduction steps

Set node version to 18 in the build settings and start a new deployment.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by saharl-neosec** [comment]
Having this issue as well
Build machine image is set to `Amazon Linux 2`
Thinking of creating my own image just to satisfy this need

**Comment by kivohin** [comment]
Exactly same issue here when switching from Node.js 16 to Node.js 18.

So I had to downgrade again for now to Node.js 16.

**Comment by alana314** [comment]
even node 16 is giving me this issue. Anyone have a public image to use in the meantime?

**Comment by alana314** [comment]
an amplify custom image of node:18 worked for me.

**Comment by deivyrene** [comment]
This custom image worked for me: `public.ecr.aws/t7o4u3y2/node-18.2.0:latest`

**Comment by Eishi2012** [comment]
I tried using nodejs 18 image - build was successful but the logs show that it's still using nodejs16 😔

**Comment by frattaro** [comment]
Well, v16 is end-of-life 2023-09-11, which is 5 months from now. I hope this fix drops soon.

**Comment by lucaghera** [comment]
We used `public.ecr.aws/docker/library/node:18.13.0` and it's working fine.

**Comment by kylekirkby** [comment]
> We used `public.ecr.aws/docker/library/node:18.13.0` and it's working fine.

This was what worked for me too. 

My frontend build failed because no 'aws-exports' file was being generated when using the `node:18.14.2` build image (amplify: command not found etc).

**Comment by panudetjt** [comment]
No sharing solution worked for me because missing aws-cli

```shell
aws codecommit credential-helper $@ get: 1: aws: not found
```

**Comment by angelinfante** [comment]
> Thanks for opening this issue. Amazon Linux 2 doesn't support the right GLIBC version at the moment, we're coordinating internally to get that updated. As @saharl-neosec mentions, you can provide a custom docker image until we fully support it:
> 
> https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html

@calavera What is the ETA of the update? It is hard to believe that an out-of-the-box solution is no set available.

Thank you in advance.

**Comment by hhemmati81** [comment]
@calavera so that you know we cannot use custom docker images due to compliance. We can only use AWS-certified images.

**Comment by kachkaev** [comment]
I have also struggled to upgrade Node.js to v18 inside Amplify. When using using a default base image, I see this:

<img width="1092" alt="Build image updated on: 11/08/2021; List of not versions includes ... 16, 17 but not 18" src="https://user-images.githubusercontent.com/608862/230135764-c2f169ac-4726-4a62-ab39-5ece103b193e.png">

Trying `amazonlinux:2023` as a base image failed for me with `/bin/sh: line 1: git: command not found` in _Cloning repository_ stage. I also tried `public.ecr.aws/docker/library/node:18` but it failed too with this error from Next.js (_Frontend_ stage): 

```
2023-04-05T15:36:05.196Z [WARNING]: ./src/path/to/some/file.tsx:7:23
                                    Type error: Cannot find module '../../aws-exports' or its corresponding type declarations.
```

A closer inspection of revealed that the actual error happened in the _Backend_ stage, it just did not produce a non-zero exit code:

```
023-04-05T15:35:42.004Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2023-04-05T15:35:42.004Z [WARNING]: /codebuild/output/src449645590/src/project-name/amplify.sh: line 21: amplify: command not found
2023-04-05T15:35:42.005Z [INFO]: # Completed phase: build
```

I guess all our team can do is to stick with Node 16 for now, which quite a shame given that Node 18 [has been](https://github.com/nodejs/Release) in active LTS phase since 2022-10-25 (nearly six months from now). Node 16 reaches its end of life in [2023-09-11](https://nodejs.org/en/blog/announcements/nodejs16-eol), which is quite soon. Using a default image and seeing _Build image updated on: 11/08/2021_ does not feel very secure.

If anyone manages to get Node 18 working in Amplify (especially with the _Next.js - SSR_ framework), please share your recipe! Hope that someone from Amplify can help us here soon 🙏

**Comment by olliethedev** [comment]
@kachkaev I got node18.x working on the backend. I had to both use a custom image and manually set the node package version:

![Screen Shot 2023-04-13 at 7 18 55 PM](https://user-images.githubusercontent.com/5933733/231903428-3ad9a3ad-2eea-4161-b95d-ee4514d15d91.png)

**Comment by yassinecc** [comment]
@olliethedev I still see node 16 in my Lambda logs after using the Node 18 build image + overriding the node version with `18`, do you have your cloudformation template json included in your source code?

I don't see it anywhere with the Next JS starter boilerplate + simple amplify hosting with Github

**Comment by olliethedev** [comment]
Great question. I only needed `nodejs18` for a rest api lambda function `amplify/backend/function/{api_name}/{function_name}-cloudformation-template.json.` 

Im not exactly sure where the template for NextJS backend would reside. Maybe some one from Amplify side can help answer that for you. 🤓

**Comment by Narrator** [comment]
Hi everyone, we now have Node 18 available in the default Docker image for all builds! The version is pinned to `18.13.0`, which you can leverage by simply adding the `nvm use 18` command to your build spec.

Unfortunately, you will not be able to use Live Updates with Node 18 - So you will not be able to use any other minor/patch version of Node 18. This is because of a limitation with Amazon Linux 2, where Node 18 needs to be built from source. We have however built `18.13.0` from source and baked that into the image.

If you need any other minor/patch version of Node 18, please install it from source like so:
```
nvm install -s 18.x.x
```

Please note though that this will increase your build time.
