### ISSUE TITLE
Amplify Next 13 Web Compute - CloudFront Distribution

### ISSUE THREAD

**Issue by renchris** [aws-amplify/amplify-hosting#3125]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2wzxfgylxxfth

### AWS Region

us-west-2

### Amplify Hosting feature

Redirects

### Describe the bug

I have recently migrated my NextJS Amplify application to Web Compute. There seems to be some configurations incorrectly changed during migration that had my web application inoperable ie. I had to re-edit the "Rewrites and Redirects" to the back to default Source address /<*>  to Target address /index.html

I am trying to locate the CloudFront distribution of my Amplify application so I can set up a CloudFront function for HTTPS redirects.

However, the two CloudFront distributions that I see available are those of my previous branches before the migration. The branches do not correspond to my current main Github branch and Amplify application URL.

How do I locate and access the CloudFront distribution of my current Amplify application so that I may associate my CloudFront function?

### Expected behavior

I expect to find the CloudFront distribution of my Amplify application available. If I were to enter in the Distribution domain name I expect to see the same webpage of my hosted application

### Reproduction steps

1. In my AWS dashboard, go to my application in Amplify. Open the application URL of my hosted domain. See that it is current
2. In my AWS dashboard, go to my distributions in CloudFront. Open the Distribution domain name of my distribution. See that it is not the same as my current application. 

### Build Settings

```yaml
version: 1
 
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
```

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I am following this tutorial to set up a CloudFront function but don't have the Amplify application CloudFront distribution to attach it to: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/functions-tutorial.html

**Comment by evan1715** [comment]
I've been toying with it all day, trying to analyze what actually changed. From what I'm seeing, and I could be wrong, this is what I've gathered: You're not using CloudFront after the migration because the new set up does not use Lambda Edge functions. It's regular Lambda distributed in your designated region.

Basically, putting Next on Amplify is now like a regular React app in the way it is set up to be distributed. I assume that's also why middleware is now enabled too.

Amplify failed to inform us of the thorough details when suggesting to migrate, which is something that should not be looked over. We should've been given far more details on the exact differences. If you look at the docs, they don't mention Lambda at Edge for Next 12 & 13. They're now only mentioning it for Next 11.

You can try to use that command they provided when you hit the migrate button so you can roll back to it... unless you didn't save the command. Something that Amplify should have also made available to use instead of disappearing once the modal closed.

I wouldn't call this scenario a bug because I've actually wanted to not be forced to use the edge & be forced to deal with the costs because it's 3x more expensive compared to regular Lambda. I definitely prefer it the way it is now. However, if the Amplify team does bring Lambda Edge back, please only do so if you make it opt-in only and not the default with NextJS.

If you absolutely require edge caching/global CDN for your website, you can use Vercel for edge (they use AWS for their edge and hosting), create your own edge functions through the separately outside of Amplify, or try the serverless framework to do a mixture of different things outside of the annoyances of the AWS console.

**Comment by evan1715** [comment]
I've been toying with it all day, trying to analyze what actually changed. From what I'm seeing, and I could be wrong, this is what I've gathered: You're not using CloudFront after the migration because the new set up does not use Lambda Edge functions. It's regular Lambda distributed in your designated region.

Basically, putting Next on Amplify is now like a regular React app in the way it is set up to be distributed. I assume that's also why middleware is now enabled too.

Amplify failed to inform us of the thorough details when suggesting to migrate, which is something that should not be looked over. We should've been given far more details on the exact differences. If you look at the docs, they don't mention Lambda at Edge for Next 12 & 13. They're now only mentioning it for Next 11.

You can try to use that command they provided when you hit the migrate button so you can roll back to it... unless you didn't save the command. Something that Amplify should have also made readily available to use instead of disappearing once the modal closed. You _might_ be able to find it buried in the docs.

I wouldn't call this scenario a bug because I've actually wanted to not be forced to use the edge & be forced to deal with the costs because it's 3x more expensive compared to regular Lambda. I definitely prefer it the way it is now. However, if the Amplify team does bring Lambda Edge back, please only do so if you make it opt-in only and not the default with NextJS.

If you absolutely require edge caching/global CDN for your website, you can use Vercel for edge (they use AWS for their edge and hosting), create your own edge functions separately outside of Amplify in the AWS console, or try the serverless framework to do a mixture of different things outside of the annoyances of the AWS console.

**Comment by swaminator** [comment]
@renchris @evan1715 please refer to: https://aws.amazon.com/blogs/mobile/amplify-next-js-13/. With Next.js 13 we launched a fully managed service to run your SSR and API routes instead of deploying some resources in your account. Please refer to https://aws.amazon.com/amplify/pricing/?nc=sn&loc=4

**Comment by michrome** [comment]
Adding a further clarification to confirm after migration, the CloudFront for your app is fully managed by Amplify Hosting and is not listed in your AWS account.
