### ISSUE TITLE
AssumedRoleToken expires after 1h

### ISSUE THREAD

**Issue by hackmajoris** [aws-amplify/amplify-hosting#3126]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

xxx

### AWS Region

eu-central-1

### Amplify Hosting feature

Build settings

### Describe the bug

The Assumed Role Token which Amplify Console is using, expires after 1h, even if it is set to expire in 4h(max allowed in IAM)
In my case, with @Searchable annotation and other additionals pre-build steps, the build takes more then 1h(first build).
I also have post-push configured.
When it finishes the buld step, the hooks run with an error, because of the token expiration.
<img width="720" alt="Screenshot 2022-11-19 at 12 35 31" src="https://user-images.githubusercontent.com/3758212/202853689-0ac53bad-7de3-496d-aec1-42fe42cb6549.png">

### Expected behavior

The Assumed Role Token takes in consideration the value set in IAM

### Reproduction steps

1. You need a build which takes more then 1h. In my case, with @Searchable annotation and other additionals pre-build steps, the build takes more then 1h.
2. Have post-push hooks condigured.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @hackmajoris :wave: , thanks for reaching out to us and apologies for the delayed response on this thread.

When a backend build is initiated, Amplify Hosting’s build session role assumes your Amplify app’s IAM service role to deploy/update backend resources using temporary security credentials.

Unfortunately, we do not have a way to increase the token expiration to more than an hour because this limitation is enforced by IAM on the role chaining duration: https://repost.aws/knowledge-center/iam-role-chaining-limit

It seems that long backend build duration (> 1hr) can typically occur if your app has a large schema defined in the amplify backend. Our recommendation would be to chunk out or split your changes in the schema. For example, if you were modifying/updating 4-5 relationships at once in your schema, try to update only a couple of relationships at once to see if that reduces the backend build duration. Additionally, since your app requires some pre-build steps you can consider using a [custom build environment](https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup) as you can pre-install specific dependencies that usually take longer to install during a build using Amplify's default container and you can speed up this process by creating your own Docker image and reference it during a build.

I am going to close this GitHub thread in favor of https://github.com/aws-amplify/amplify-hosting/issues/2751 to avoid duplicates and please feel free to track/monitor it for further updates.
