### ISSUE TITLE
Can't found Next.js logs in new Web_Compute mode

### ISSUE THREAD

**Issue by CauanCabral** [aws-amplify/amplify-hosting#3148]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1ozne3e1ut3gj

### AWS Region

sa-east-1

### Amplify Hosting feature

Access logs

### Describe the bug

Have a Next.js 12.2 application running in `Web_Dynamic` mode, and when I need it, I go to CloudWatch and look for access and error logs from Lambdas SSR, ISR, and API.

Since we have the release of `Web_Compute` last week, I did a try to deploy the same code in a new project.
The build was success, but when I try to look at new logs, I always get "Not found resource" from the console:

![image](https://user-images.githubusercontent.com/83092/203991189-f44d288e-5c99-43ea-a965-61701890265a.png)

I tried to search the Log Group in different regions (sa-east-1, us-east-1, us-east-2, us-west-1, us-west-2) and don't found nothing.

### Expected behavior

A way to read the logs from my app.

### Reproduction steps

1. Add a new project
2. Build the project
3. Go to menu "Monitoring"
4. Go to tab "Hosting compute logs"
5. Click on log group

![image](https://user-images.githubusercontent.com/83092/203992134-3be86692-4153-4b12-bc6b-4069e7b54a4a.png)

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ferdingler** [comment]
Hi @CauanCabral, can you verify please if the IAM role associated to your Amplify App has permissions to write to CloudWatch logs: 

```
logs:CreateLogStream
logs:PutLogEvents
logs:CreateLogGroup
```

Also, check the trust policy in the role and make sure that your role trusts Amplify: 

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "amplify.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

**Comment by CauanCabral** [comment]
Hi @ferdingler , I asked our account administration and they can't find any log groups with that name - besides it has Administration privileges.

Our service account role (used by Amplify) and my personal account also have the mentioned permissions.

It seems to me the log groups **or don't exist**, **or aren't visible for our administration accounts**.

**Comment by Jay2113** [comment]
Hi @CauanCabral 👋 , thanks for your continued patience and we apologize for the delayed response on this thread.

It seems that your Amplify app `d1ozne3e1ut3gj` has been deleted. I just wanted to check in with you to understand if you are still running into this behavior with other Amplify Compute apps?

If yes, here are a few things that you can review on your end:
- When you deploy a Next.js SSR app, the app requires an IAM service role that Amplify assumes to send information about your Next.js runtime to Amazon CloudWatch Logs in your AWS account. This [documentation](https://docs.aws.amazon.com/amplify/latest/userguide/ssr-CloudWatch-logs.html) outlines the permissions necessary on the IAM role.
- Amazon CloudWatch enforces the following quotas on log groups that might be relevant to your account and thus kindly review if your account isn't being throttled due to exceeding any of the quotas:
  - [CreateLogGroup API](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html) has a rate limit of 5 transactions per second per account per region.
  - You can create up to [1,000,000 log groups per account per Region](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html).
- I was able to reproduce similar CloudWatch console banners that were visible to you, when I navigated to a different AWS region in the CloudWatch console. Kindly ensure that you are logged into the appropriate AWS region when searching for the log group.
- Lastly, you can also review if there are any [Service Control Policies (SCPs)](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html) that are enforced on your account or organization which could be taking precedence/overriding the permission on the IAM service role.

NOTE: The creation of the IAM service role and the Amplify log group CloudWatch resource in your account, for a Next.js Compute app might not be instantaneous (with the app creation) as there could be some propagation delay.

I hope these detailed insights are helpful to you!
