### ISSUE TITLE
CloudFront and App Domain are different after migration

### ISSUE THREAD

**Issue by 0618** [aws-amplify/amplify-hosting#3158]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d38nl2e2iyazfs

### AWS Region

us-east-2

### Amplify Hosting feature

SSR

### Describe the bug

After migrating from Next.js11 to Nextjs12 and change WEB_DYNAMIC to WEB_COMPUTE, the domain doesn't work and return a 500 error from cloudfront.

But the CloudFront domain from Next.js11 build still works with the older commit.

### Expected behavior

Either the cloudfront domain should have the same behavior as the Amplify Hosting domian, or it should not be accessible at all.

### Reproduction steps

Same step as https://github.com/aws-amplify/amplify-hosting/issues/3153

1. Start to host a Nextjs 11 app (appID: d3sci3ahfz8hus, appID: d2213k35dz5phy)
2. Migrate to Nextjs12
3. When the build is done, to do domain. Note the CloudFront distribution ID.
4. Got 500 errors from CloudFront
5. Go the CloudFront distribution ID, go to the CloudFront Domain xxxx.cloudfront.net (No error)

### Log output

<details>

```
Error: Cannot find module '@swc/helpers/lib/_async_to_generator.js' 


```

</details>

**Comment by foobarnes** [comment]
I'm experiencing the same issue.

App ID: d263pg34gxs8oh

**Comment by ferdingler** [comment]
Hi, thanks for bring this up. 

It looks like there is a missunderstanding in how the new _web_compute_ platform works, and  will make sure to improve our documentation to avoid these confusions. To clarify, in the _web_compute_ platform, we no longer deploy resources (CloudFront distributions, L@E, S3 buckets, etc) in your account. Instead, the infrastructure is fully managed by Amplify Hosting. The reason you still see the old resources in your account is because we do not delete them when you migrate to web_compute so that you have the option of rolling back to the previous platform web_dynamic if you want to. 

Now, one thing that I noticed on my end is that these particular app Ids `d263pg34gxs8oh`, `d3sci3ahfz8hus` mentioned above, still have Rewrite Rules configured that point to the previous CloudFront distribution in your account. For example: 

![Screen Shot 2022-11-30 at 1 22 52 PM](https://user-images.githubusercontent.com/3701083/204910851-b973eb1b-5e28-43bd-b08d-bc8515627caf.png)

These rules should have been deleted automatically by Amplify Hosting when you migrated to web_compute, so this seems like potentially a bug on our end that I will follow up on. For now, feel free to remove them yourself manually in the Console so that the requests are no longer redirected to the old distribution. 

If you are experiencing 5xx errors after migrating to web_compute. You can check the logs in CloudWatch to see what error is being thrown in your SSR pages or API routes. You'll find a CloudWatch log group named `/aws/amplify/{yourappId}`. 

Finally, if you decide to go back to the web_dynamic platform for whatever reason. You can do so by running these commands using the AWS Command Line Interface: 

```bash
aws amplify update-app --app-id {your_app_id} --platform WEB_DYNAMIC
```

and then run a new build as normal.

**Comment by foobarnes** [comment]
Thanks for the help @ferdingler! To confirm, should I delete all of the rewrite rules in our app that target any Cloudfront distribution? What about the rewrite mentioned [here](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa)?

Thanks again!

**Comment by ferdingler** [comment]
@foobarnes you should only delete the ones with `source=/<*>` and `target=https://something.cloudfront.net. Each one of those rules is for a different branch. Unfortunately the Console doesn't show which rule is for which branch, so you can figure that out by identifying the distribution in the Deployment logs for each branch.

**Comment by foobarnes** [comment]
Worked like a charm! Thank you 🙏🏻

**Comment by kivohin** [comment]
Hi @ferdingler. As I mentioned in my comment here:
https://github.com/aws-amplify/amplify-hosting/issues/3131#issuecomment-1343261229

One of our problems were the old rewrite rules pointing to some old distributions after the migration to the `web_compute` platform.

The second problem we faced, is that we were not managing our custom domain through Amplify's `Domain management` section. Instead we had everything configured directly in Route53.

Is this change in direction where the infrastructure is fully managed by Amplify Hosting going to be permanent? For us this was one of the main reasons we chose Amplify over Vercel/Netlify, since we still had control over the infrastructure.

**Comment by 0618** [comment]
(Sorry for the late reply because I had to switch my gear.)

I'm not seeing the redirection to the old cloudfront though

![image](https://user-images.githubusercontent.com/11983489/206574705-791c703c-f285-45b9-a323-9e32b85ff85d.png)

**Comment by MaximeIJ** [comment]
The two fixes mentioned should be part of the Nextjs migration documentation!

@ferdingler : It totally makes sense to leave the resources up to allow for a rollback. What is the guidance on deleting them once the migration has been verified to work and a rollback is no longer on the table? Is there a list of resources that are no longer in use?

**Comment by Develliot** [comment]
Hi I just ran into this issue and deleted the old rewrite entries as mentioned above, before reading all this. I managed to get things working, but also spent the last day freaking out about how to retrieve the new cloudfront URLs assuming that things are going to break again when I have branch pattern deploys adding new entries into the rewrites, so I'm breathing a sigh of relief here after reading this thread. +1 for adding this to the documentation or making it super clear somewhere.

I'm actually super glad that it works this way because I was running into issues previously where each new branch build was creating re-writes that were higher in the order of preference to my custom re-writes, which stopped my custom re-writes from working and I would have to re-order them after each branch deploy. I'm guess this issue is in the past now because it's is all happening behind the scenes.

**Comment by Develliot** [comment]
I did this on my production app which doesn't have branch name pattern deploys and it was seamless, It worked with the custom domains and removed the cruft from the rewrites, which didn't happen in my staging app. I don't really know why one worked and the other needed a bit of manual work
