### ISSUE TITLE
It is not connecting properly with the domain

### ISSUE THREAD

**Issue by Elektroi** [aws-amplify/amplify-hosting#3222]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

m-fa01ece1955f400bbf8affd68dac2146

### Region

eu-west-1

### Step

Domain activation

### Status

Failed

### Issue or question

This app was working and suddenly stop working.
I have this domain in route 53 and it works for amazon workmail.
But in the case of amplify is not working.
I have reviewed the domain but I don't know what else to do.

### Error message

Error message: One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by anurag128** [comment]
Is this domain linked with any other resource like CloudFront or API Gateway Custom domain in your account?
Also refer below Knowledge Center article:
https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

**Comment by Elektroi** [comment]
I linked it automatically with the tools that the Amazon workmail provides.
They do it automatically so I don't know how to see it.
When I go inside CloudFront there is nothing there.

**Comment by hloriana** [comment]
Hi @Elektroi can you provide your app ID or the custom domain you're trying to add so we can see what is causing the error?

**Comment by Elektroi** [comment]
The domain is abaraskaetxea.eus and this is the arn of the application
arn:aws:amplify:eu-west-1:719270881588:apps/db3kv6rw5o8ey

**Comment by Jay2113** [comment]
@Elektroi 👋 , thanks for providing us that information. The domain abaraskaetxea.eus is already connected to an Amplify app `d2m33ds2ik6p0x` which resides in the same AWS Account as Amplify app `db3kv6rw5o8ey`.

If you would like to connect this domain to the Amplify app `db3kv6rw5o8ey`, you will then need to first delete the domain association from the Amplify app `d2m33ds2ik6p0x` and then retry the domain activation process in the Amplify Console.

Just a side note, I went ahead and have redacted the AWS Account ID from your previous response due to security concerns.

**Comment by Elektroi** [comment]
I removed and created again.
When it arrives to domain activation appears:
Error message: One or more of the CNAMEs you provided are already
associated with a different resource.
Yes that domain is associated with the Amazon Workmail but I suppose that
they are not in conflict...

**Comment by stephen-w-choo** [comment]
Hello! I hope you don't mind me piggybacking on this issue - I'm having a similar issue as well.

Jay, if you don't mind me asking, how do I check if a domain is already connected to another Amplify app or Cloudfront distribution? I went into the Cloudfront page, but it says no distributions currently exist - I'm not sure how to delete whatever it is that's conflicting with my current domain.

**Comment by stephen-w-choo** [comment]
So I ended up making a ticket and it turns out there was an identical Amplify distribution in a different region (North America).

I have absolutely no memory of doing this - I'm in the APAC region, but I must have done so at some point. 

You might have to go through Amplify manually in each region to check for other apps with the same name thay may have been deployed there

**Comment by hloriana** [comment]
@Elektroi I tested a scenario with using the same domain for an Amplify app and Amazon Workmail organization and there was no conflict with CNAME records. In your case, there is another Amplify app already associated with abaraskaetxea.eus. Please make sure you check your other Amplify applications including any apps in other regions to ensure you properly remove the current domain association.
