### ISSUE TITLE
How do I add environment variables to React app? Modifying amplify.yaml causes build error. 

### ISSUE THREAD

**Issue by HuckleberryKBT** [aws-amplify/amplify-hosting#3300]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2s35pqb094ts4

### AWS Region

us-east-1

### Amplify Hosting feature

Build settings, Frontend builds

### Question

I have found quite a few resources that explain how to add env variables to the amplify yaml file - but all of them cause my build to fail.  I am not changing anything else except for the build command and it fails with env variables, but if I remove them and redeploy my app deploys with no issues. I have tried both variations below, one from a medium article and one directly from aws, but both cause my build to fail.  What is the appropriate way to add env variables to a react application hosted on amplify?

`version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - REACT_APP_GA_ID=${REACT_APP_GA_ID}
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
`
and this one

`
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build:$BUILD_ENV
        - echo "REACT_APP_GA_ID=$REACT_APP_GA_ID" >> backend/.env 
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - `

**Comment by hloriana** [comment]
Hi @HuckleberryKBT the second variation is the appropriate way to reference the environment variable. Your build was breaking during the backend phase when you executed that variation of build commands. 

The build failed due to `Invalid feature flag configuration` which can happen if Amplify is using an older version of the CLI than what your app is using locally. You can pin the correct version of the CLI using live package overrides: https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates
