### ISSUE TITLE
Failed to connect backend env to multiple frontends 

### ISSUE THREAD

**Issue by build-for-life** [aws-amplify/amplify-hosting#3314]

**Comment by hloriana** [comment]
Hi @atef-abdellatif 👋🏽 are you connecting a frontend to a backend belonging to the same app or a different app?

I walked through the reproduction steps and was able to successfully connect my frontend to another backend in the same app and also in a different app. I was also able to deploy the apps and view the backend resources in Amplify Studio.

>  I saw the connected backend shown in the backend environment tab with all categories added which was great, but once I refreshed the page it went away as if it never connected!!! 

Is this behavior consistently happening? If so, could you provide a screenshot, video, or GIF of this?

**Comment by atef-abdellatif** [comment]
Hi,

Thank you so much for your reply!

I’m actually trying to connect a frontend to backend belonging to a different app. Yes, this behavior is constantly happening. I couldn’t attach my screen recorded video because it was 9mb so I uploaded it on retransfer.com and you will find the download link below. You will notice that after I connect the backend it shows under the backend environment tab with all the added categories but once I refresh the page it just vanishes!

Wetransfer download link: 
https://we.tl/t-7V8jeqTCtx

Best,
Atef
