### ISSUE TITLE
Does cloning a backend env in the Amplify Console also copy the data?

### ISSUE THREAD

**Issue by kimfucious** [aws-amplify/amplify-hosting#3331]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3ljtdngtdwxhk

### AWS Region

us-west-2

### Amplify Hosting feature

Deployments

### Question

Hi there,

I am re-thinking my workflow with Amplify, and my aim is to simplify.

Prior, I had three backend environments and three git branches.

Basic workflow:

1. `git switch -c feature` 
2. `amplify env checkout dev` (reusing dev env, as there's test data there)
3. Do work and test
4. If good (assuming no backend changes):  `git switch test`, `git merge feature`, `amplify env checkout stage`, `git push`
5. Test stage.  If good, do 4 for master.

This felt cumbersome, and was often confusing with regard to the changes happening as a result of switching environments.  I was doing `amplify push` without knowing what changes were actually made.

Enter Previews! 🎉 

I've basically wiped all backend environments and connected branches except prod(amplify env) and main (git).

I've configured Previews on the connected main branch so that pull requests (and subsequent changes to those pull requests) create a preview.  At present, I'm using the prod backend for this.

This is great!  Work flow is much simpler:  test in preview and when it's good merge the PR and done.

What I thought might be better is to clone prod and use the clone as the backend for previews.  I've not done this yet.

QUESTION 1:  If I clone prod in the Amplify Console, will it also copy the data?

This would be ideal, as I wouldn't have to recreate stuff (and it's a lot) every time a new feature is embarked on.

QUESTION 2:  Is there a better way to streamline this process, or am I overlooking anything that might not want me to be doing this?

Thanks  🌮 !

**Comment by hloriana** [comment]
Hi @kimfucious 👋🏽 thanks for raising these questions. 

1. If you clone your production environment, a new backend environment will be created with the same resources deployed. However, the data in your prod environment **will not** be copied over. So for instance, if you have an S3 bucket as part of your backend resources in your prod environment, a new S3 bucket will be provisioned in the cloned environment but it will not contain any data. 

2. You're already on the right path by using previews test out changes. If your backend environment has a lot of data/resources, then you can certainly create a test backend environment and point all previews to that environment instead of prod. That way you don't have to create a new backend for every preview and also avoid testing on your production data.
