### ISSUE TITLE
URL not working without 'www' after 'https://'

### ISSUE THREAD

**Issue by NicoVelazquez** [aws-amplify/amplify-hosting#3354]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2k8ta4b8b9p58

### Region

us-east-2

### Step

Domain already connected

### Status

Failed

### Issue or question

Currently my domain is working fine when entering 'https://www.domainName.com'. 

The problem is when removing the 'www'. When I enter 'https://domainName.com', the site does not load. 

It does work with 'http' with and without the 'www'. 

Im attaching a screenshot of my "Domain Management" configuration and my "Rewrites and redirects" config.

<img width="1359" alt="Domain managment" src="https://user-images.githubusercontent.com/20953958/223414937-02886cd2-6225-4b02-ad6e-2d6b59dfc06d.png">

<img width="1351" alt="Rewrites" src="https://user-images.githubusercontent.com/20953958/223414944-db879f9f-f98e-4567-90c4-61d7d6efedec.png">

### Error message

<img width="768" alt="Chrome Error" src="https://user-images.githubusercontent.com/20953958/223415131-dbd6a4b2-62b5-4eae-9dc3-1389a7256e39.png">

**Comment by hloriana** [comment]
Hi @NicoVelazquez 👋🏽 thanks for raising this issue. The http://domain.com url is working because the traffic is being redirected to https://www.domain.com:

![Screenshot 2023-03-07 at 12 23 24 PM](https://user-images.githubusercontent.com/76065904/223516294-11008c8c-587b-4de5-b31e-239426b29e41.png)

I have a few questions that can help with investigating this:
1. What DNS provider are you using?
2. Do you have an ANAME record configured to point to your root domain? If you are using a 3rd party provider, you will have to create an ANAME record that points to your root domain. This is outlined in step 12: [Add a custom domain managed by a third-party DNS provider
](https://docs.aws.amazon.com/amplify/latest/userguide/to-add-a-custom-domain-managed-by-a-third-party-dns-provider.html)

**Comment by NicoVelazquez** [comment]
Hi @hloriana, 

Thanks for your response. 

Im currently using GoDaddy. GoDaddy does not let me set ANAME records. 

Nevertheless, I used to have an application hosted in Amplify and didn't have this issue. 

Is there any solution to this? What is strange to me is that when configuring the domain in AWS Amplify, there is a toggle to activate 'https://domain.com' to  'https://www.domain.com', but it doesn't appear to be working. Im attaching a screenshot of this toggle. 

<img width="1680" alt="Screen Shot 2023-03-06 at 17 03 10" src="https://user-images.githubusercontent.com/20953958/223522339-ca95e307-0a53-4b8c-8521-e2219247485e.png">

**Comment by NicoVelazquez** [comment]
I've already solved this issue by transferring my domain host to CloudFlare. Apparently Cloudflare fixes this issue by using what is called CName flattening that works like having an ALIAS (they use this by default - you don't have to do anything else than configuring your nameservers and adding DNS records.
