### ISSUE TITLE
Amplify console for dummies.

### ISSUE THREAD

**Issue by ImJimORourke** [aws-amplify/amplify-hosting#3367]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

NEW_APP

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Question

Looking for some friendly help to guide me on using the AWS Amplify web console to deploy a web app.  Here is what I did in the console to get to a failure point:

1. Click New App >> Host Web App
2. Select GitLab repository >> click Continue
3. GitLab authorization successful && selected repository && selected branch >> click Next
4. Added app name
5. Left auto-detected app build settings as is:  

version: 1
frontend:
  phases:
    # IMPORTANT - Please verify your build commands
    build:
      commands: []
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /
    files:
      - '**/*'
  cache:
    paths: []

6. Checked "Allow AWS Amplify to automatically deploy all files hosted in your project root directory"
7. Opened Advance Settings && added to Build Image: "docker-compose.yml"  >> clicked Next
8. Clicked Save and deploy
RESULTS: Provisioning failed ... "[BUILD_CONTAINER_UNABLE_TO_PULL_IMAGE: Unable to pull customer's container image. CannotPullContainerError: Error response from daemon: pull access denied for docker-compose.yml, repository does not exist or may require 'docker login': denied: requested access to the resource is denied]"

The docker install instruction from the public git are very simple:
docker install
Install git, docker and docker-compose.
Note: don't forget docker's post-installation steps! ([eg for linux](https://docs.docker.com/engine/install/linux-postinstall/)).

Fetch the source:

$ git clone https://gitlab.com/<the git>

Copy the environment variables file

$ cd <to the directory> && cp variables.env_example variables.env  

Pull and run the docker containers

$ docker-compose pull
$ docker-compose up -d  
You should be able to access the website at http://localhost:8080/

Rookie warning! I have never deployed an app before, but I follow instructions well.  

I searched the internet and youtube for any guidance on using the Amplify console to deploy a dockerized application, but all guidance found uses command lines, not the Amplify console app setup web interface. 

Where did I go wrong attempting to learn this process?  Does anyone care to make a video on how to use the Amplify console to deploy a docker container?

**Comment by hloriana** [comment]
Hi @ImJimORourke 👋🏽 thanks for raising this question!

Amplify Hosting supports serving static web applications using popular frameworks like React, Vue, Angular, Gatsby, etc. and SSR applications using Next.js framework. During the build process for CI/CD applications, we run a build of your application using the specified build command (ex. `yarn run build`, `npm run build`) and then we serve the build artifacts. 

Currently, deploying a containerized application using Amplify is an advanced workflow available via the Amplify CLI. Your application will actually be deployed to AWS Fargate during this workflow. This is because Amplify Hosting does not have container engines that run as host containers for your application. That is why the advanced workflow will have you deploy your application with AWS Fargate instead which is a serverless compute engine for containers. 

Please see [Advanced Workflows: Serverless containers](https://docs.amplify.aws/cli/usage/containers/) for more instruction for deploying your application.

**Comment by ImJimORourke** [comment]
Thank you for the reply.  I guess I am a bit confused as the the purpose and functionality of the Advanced settings
>> Build image feature of the web console?  Could you elaborate?

Advanced settings
Build image
Use our default build container, or provide your own. [Learn more](https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html)
Reference your build image (E.g. <docker repository>/<docker image name>)

**Comment by hloriana** [comment]
Hi @ImJimORourke sure, let me provide some further explanation. Those settings allow you to use your own custom build image instead of the image that Amplify uses by default. If you need to leverage specific dependencies that are not part of the default build image, then it can take a significant amount of time to install those dependencies. 

The solution for this is to use your own Docker image that has the required dependencies which can reduce overall build times in this scenario. Please see [Custom build images](https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html) for step-by-step instruction for this. 

Does that provide clarity for you?
