### ISSUE TITLE
Next.js v13 returning JSON string to browser when leave tab open long time.

### ISSUE THREAD

**Issue by ChristopherTrimboli** [aws-amplify/amplify-hosting#3404]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1y5qktl4kit5i

### AWS Region

us-west-1

### Amplify Hosting feature

Frontend builds, SSR

### Describe the bug

When you leave the tab open for a long time, we see this page sometimes:

![code showing bug - Screenshot at Mar 29 08-03-29](https://user-images.githubusercontent.com/27584221/229907423-4a6b0bd3-45e4-4b3e-a03f-a8d2a21dcb30.png)

We traced the errors in log, and looks like extension bugs... so we tested with fresh alternative browsers on multiple devices with no extensions installed... still reproduced.

Then, we installed our exact same code on Vercel... it fixed this issue. 
Our hunch is some service is timing out the SSR in Amplify?

We have another codebase same Next 13, but much different code, simpler... and it happens with that too on Amplify. So we do not think a personal code issue, as it also works in Vercel.

### Expected behavior

Do not show this JSON string.

### Reproduction steps

Go-to our website: https://therealm.gg/leaderboard

Leave tab open for awhile, browser shows JSON string.

### Log output

<details>

```
# Put your logs below this line

No relevant logs we could find.

```

</details>

**Comment by hloriii** [comment]
Hi @ChristopherTrimboli thanks for raising this issue and providing us reproduction steps. We will try to observe this behavior on our end and determine the cause. We will update this issue with next steps once we understand the issue.

**Comment by hloriii** [comment]
I was unable to observe this behavior with your application and I was unable to replicate this. Have you experienced this with boilerplate Next.js code? Could you please provide a repo that produces this behavior so we can reproduce on our end?

**Comment by marketsystems** [comment]
had this happen to me today when clicking back on browser, page full of json instead of the website.

**Comment by jaime-skupee** [comment]
In my team we also had this issue on Amplify exactly for Nextjs projects, and we found it happens mostly when we use the new appdir and the 13.2.4 version, we found is mostly for our case a problem with the new router not working properly with the browser cache.

What we did to address the problem was to return to pages dir, and downgrade the Next version to 13.1.6

**Comment by hloriii** [comment]
@jaime-skupee thank you for providing additional context for this issue. I tried testing this with Next.js version 13.2.4 with the app directory feature enabled but have not ran into this issue yet. 

When this issue was occurring for you, did the JSON only appear when leaving the tab open for an extended time? If so, how long did you have to leave the tab open? Did you have to click around the app to eventually run into this? Did you experience this behavior consistently or just occasionally?
