### ISSUE TITLE
Deploy fails with msg "Failed to deploy"

### ISSUE THREAD

**Issue by dotsource** [aws-amplify/amplify-hosting#3429]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d32d4tvwgm1was

### AWS Region

us-east-1

### Amplify Hosting feature

Manual deploys

### Describe the bug

My manual deploy zip file has about 8000 files but the total size is around 40MB only its failing with the following info

[INFO]: Updating Edge config
[ERROR]: Failed to deploy

### Expected behavior

Complete the deployment

### Reproduction steps

Create a zip file with lot of file and use manual deploy

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by AhmedSamy** [comment]
I have the same issue here too
`eu-central-1` `des6wxtp3eafh`

**Comment by hloriii** [comment]
Hi @dotsource 👋🏽 thanks for raising this issue. It appears you have since deleted your application so I'm unable to investigate the cause of your build failure. Can you provide a dummy zip file that reproduces the behavior?

**Comment by hloriii** [comment]
Hi @AhmedSamy 👋🏽 , your deployment is failing because your application's build output is exceeding our internal limit of 220 MB. We suggest taking steps to reduce the total size of the build output. This can include reducing the size of image assets for instance. We are working on improving this limit.

If you need further assistance, please open a new issue since your scenario is unrelated to the original issue. Thank you!
