### ISSUE TITLE
404 error on page of successful deployment React Build

### ISSUE THREAD

**Issue by Geckogiggles** [aws-amplify/amplify-hosting#3435]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

https://us-east-2.console.aws.amazon.com/amplify/home?region=us-east-2#/d19pco3rnva3k6

### AWS Region

us-east-2

### Amplify Hosting feature

Deployments

### Question

I am struggling to understand why the application works on the local server instance and then suddenly has a 404 error on deployment. The build settings have been set to "build" directory as stated in other forums (https://github.com/aws-amplify/amplify-hosting/issues/3430) . Is there something I need to do in our build to get the front and back end to work congruently for Amplify to understand?
![image](https://user-images.githubusercontent.com/116981188/233187780-7daffe00-d907-4859-abde-9df330e0a09c.png)

![image](https://user-images.githubusercontent.com/116981188/233188825-f2a32714-7245-4461-bf09-394742049d92.png)

**Comment by Jay2113** [comment]
Hey @Geckogiggles 👋 , thanks for reaching out to us!

It looks like you've mentioned a couple of Amplify app id's in this thread:
- d19pco3rnva3k6
- d1ojzztvjy3ply

This issue seems to be occurring for the Amplify app `d1ojzztvjy3ply` because we are unable to detect the `index.html` file within your deploy folder i.e. the `baseDirectory` within the `amplify.yml` file.

You will need to set the `baseDirectory: build` within the `amplify.yml` file and then redeploy your app.

**Comment by hloriii** [comment]
@Geckogiggles 👋🏽 you have a typo in your build settings.

According to the screenshot, baseDirectory is misspelled. You have `baseDirector: build` set. Please replace that with `baseDirectory: build` and redeploy your app.
