### ISSUE TITLE
Getting ERR_SSL_VERSION_OR_CIPHER_MISMATCH for the subdomain containing www prefix

### ISSUE THREAD

**Issue by ozharkikh-enyo** [aws-amplify/amplify-hosting#3489]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d8t83e2f6qezu

### Region

us-east-2

### Step

Testing of the deployment

### Status

Failed

### Issue or question

For the application d8t83e2f6qezu I've connected the custom domain pfait.com for the branch "dev". The deployment was successfull and the application is available now at https://admin-dev.pfait.com (the wildcard certificate was issued by AWS for the domain *.pfait.com).

However, when I try to add the CNAME DNS record in Route 53:

www.admin-dev.pfait.com -> admin-dev.pfait.com

I'm getting the following exception when trying to open https://www.admin-dev.pfait.com:

ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### Error message

ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by nadetastic** [comment]
Hi @ozharkikh-enyo, thank you for opening this issue. At this time what you have explained is the expected behavior. In short wild card certificates will only work on the same level subdomain and would not be able to work with multi level domain. E.g., `*.a.com` matches `foo.a.com` but not `bar.foo.a.com` - more information in[ this RFC - Section 3.1](https://www.ietf.org/rfc/rfc2818.txt#:~:text=single%20domain%20name%0A%20%20%20component)

In order to have `www.admin-dev.pfait.com` working, I recommend you add your custom domain to you application as `admin-dev.pfait.com` instead of `pfait.com` then you can setup a the `www.admin-dev.pfait.com` subdomain within your application. You can reference the [Amplify documentation here](https://docs.aws.amazon.com/amplify/latest/userguide/to-manage-subdomains.html) for more information.

Let me know if you have any questions.
