### ISSUE TITLE
html webpage which is working on my machine not getting deployed in amplify

### ISSUE THREAD

**Issue by duasimran16** [aws-amplify/amplify-hosting#3491]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d32qbtlftaf7yd

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Question

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
</Error>

**Comment by hloriii** [comment]
Hi @duasimran16 👋🏽 did you deploy your app using manual deploys? If so, you must make sure that you navigate inside the build output folder and zip the contents within. Otherwise, zipping the folder itself can result in the access denied error you are seeing. 

According to our [Manual Deploy](https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html) docs:
> When you create the zip folder, make sure you zip the contents of your build output and not the top level folder. For example, if your build output generates a folder named “build” or “public”, first navigate into that folder, select all of the contents, and zip it from there. If you do not do this, you will see an “Access Denied” error because the site's root directory will not be initialized properly.
