### ISSUE TITLE
XML Access Denied

### ISSUE THREAD

**Issue by DustinKerrigan** [aws-amplify/amplify-hosting#3532]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-1:<REDACTED>:apps/d3h29ni8uti0qi

### Region

us-east-1

### Step

Accessing the website

### Status

Access Denied

### Issue or question

I have been struggling with AWS for days as I am trying to access my website publicly for the first time. No matter what I do, I always get this error "This XML file does not appear to have any style information associated with it. The document tree is shown below." with the code below it `<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>E9KBHNM927ABJ43P</RequestId>
<HostId>pgOh7Xf+Zcn7x+2fiHSwTcobEAJD0iTyvzuHDF1E0R7D0fMYaCCuZLndPKOvK90TnJm6LC4J/Pw=</HostId>
</Error>`
I have realized the re writes and re directs are not the issue, but something to do with my files in the s3 bucket. Ive made everything public, enabled ACLs, I am out of options and no matter what I do its always access denied. Any tips will help. Thank you.

**Comment by Jay2113** [comment]
Hi @DustinKerrigan 👋 , thanks for reaching out to us! I can completely understand your sentiment in regards to the errors that you are observing while trying to access your Amplify website.

It looks like you have deleted the Amplify app `d3h29ni8uti0qi` and based on the information provided I believe you were trying to perform manual deploys using Amazon S3 which allows you to publish your web app with Amplify Hosting without connecting a Git provider. Please correct me if I am wrong. 

When you create the zip folder for your app, make sure you zip the contents of your build output and not the top level folder. For example, if your build output generates a folder named `build` or `public`, first navigate into that folder, select all of the contents, and zip it from there. If you do not do this, you will see an “Access Denied” error because the site's root directory will not be initialized properly. I hope this information is helpful in resolving this error.

Lastly, I went ahead and have redacted your `AWS Account ID` which was provided in the `App Id` field in the issue template.
