### ISSUE TITLE
how change git account and repository ? 

### ISSUE THREAD

**Issue by kimjuntae1997** [aws-amplify/amplify-hosting#3564]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3a4f2qt07vq54

### Amplify Hosting feature

Not Applicable

### Question

I have a two git account.
Currently Amplify App is connected 1st git account but i have to changing another git account and repository. 
my two git account have another auth and repository.
Don't delete App

Sorry. my english is not well.

**Comment by Jay2113** [comment]
Hi @kimjuntae1997 👋 , thanks for raising this! 

Based on the information provided, I understand that your use case involves creation of a new Amplify app using a git repository which resides in a different git account. While trying to implement this workflow, you are unable to connect this new app to a different git account and repository. Please correct me if I have misunderstood your query.

Amplify uses GitHub apps to authorize access to the repositories in your account. You can add fine grained access by selecting specific repositories and even repositories in GitHub organizations that you would like Amplify to access. In order to reset this configuration, you must either delete the GitHub app or revoke permissions for the GitHub app. Please follow these steps in GitHub:

- Navigate to your profile -> Settings
- Under Integrations select Applications
- Under Installed GitHub apps search for the app associated with the AWS region you are currently working in. Click Configure
- Scroll down to the Danger zone and select Uninstall "AWS Amplify (aws-region)".

If this doesn't work then you may also have an Oauth app that needs to be disabled. In this case:
- Navigate back to your GitHub applications
- Under Authorized Oauth Apps, search for the app associated with your desired AWS region
- Select the menu button next to it and click Revoke
- Navigate to the AWS console and follow the steps to host a new app with a git provider. You should be prompted to authorize access to GitHub

Lastly, if the behavior persists try to clear your browser data (cache) before switching to a different git provider.

Hope this information is helpful!
