### ISSUE TITLE
AWS AMPLIFY CANT GET SUBDOMAIN FOR THE APP

### ISSUE THREAD

**Issue by windmillcode0** [aws-amplify/amplify-hosting#3579]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-1

### Step

Domain Activation

### Status

Failed

### Issue or question

I try to setup my domain on godaddy with AWS amplify I have a link to the full reproduction https://www.youtube.com/watch?v=he3T9Jo5wmA

### Error message

Error message: [CNAMEAlreadyExistsException] The following CloudFront distributions or Amplify Apps are already using one or more of your domains: [Distribution: *******EBGIRLL in AWS Account: ******231235]. For distributions you own, please remove the domains from them first and then retry adding your domain. For Amplify apps you own, you may already have associated this domain to another Amplify App in another account or region. You can also check our troubleshooting guide for more help: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html

### Additional information

full video reproduction, for some reason ui-preview works flawlessly https://www.youtube.com/watch?v=he3T9Jo5wmA

**Comment by windmillcode0** [comment]
# AWS AMPLIFY CANT GET SUBDOMAIN FOR THE APP


## Expected Behavior
* the root and subdomain hooks up to AWS amplify site



## Current Behavior
* I get a Error message: One or more of the CNAMEs you provided are already associated with a different resource. error
 [CNAMEAlreadyExistsException] The following CloudFront distributions or Amplify Apps are already using one or more of your domains: [Distribution: *******EBGIRLL in AWS Account: ******231235].
 when I have no cloudfront distributions


## Possible Solution
* manually go into application interanls and see whats going on




## Steps to Reproduce
[Youtube url](https://www.youtube.com/watch?v=he3T9Jo5wmA)

## Environment
Angular CLI: 16.1.4
Node: 18.16.1
Package Manager: npm 9.5.1
OS: win32 x64

**Comment by Jay2113** [comment]
Hi @windmillcode0 👋 , thanks for raising this with us and for providing detailed information on the steps you performed to troubleshoot/debug this issue.

The `CNAMEAlreadyExistsException` occurs because the subdomain `www.findmyrole.co` is currently associated to a CloudFront distribution ending in *******EBGIRLL in AWS Account: ******231235.

Can you confirm if you are the owner of the AWS Account ending in ******231235 ? If yes, you can disassociate the subdomain from the CloudFront distribution ending in *******EBGIRLL from within the CloudFront console on your end. Detailed steps are outlined [here](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error).

If you are not the owner of the AWS Account ending in ******231235, kindly reach out to me via a DM on our [community discord server](https://discord.gg/amplify). My username is `Jay Raval` and I can advise on next steps.

**Comment by windmillcode0** [comment]
Alright i just got the user name and pass I will take a look
