### ISSUE TITLE
Reading Cookies in Layout Causes Envars to Become undefined

### ISSUE THREAD

**Issue by SamKomesarook** [aws-amplify/amplify-hosting#3632]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d23cvaqyj8c05s

### AWS Region

us-east-1

### Amplify Hosting feature

Backend environments, Build settings, Environment variables, Environment secrets

### Frontend framework

Next.js

### Next.js version

13.4.12

### Next.js router

App Router

### Describe the bug

When I use the cookies function from next/headers, the environment variables become undefined. This leads to errors trying to fetch data in server components, if they rely on cookies from the request.

### Expected behavior

The environment variables shouldn't be affected by the use of the cookies function.

### Reproduction steps

1. Clone the [test repo](https://github.com/Kiwi-Biosciences/test) and deploy it to amplify.
2. Add the ADMIN_TEST env var from the amplify console, and make sure it is echoed into a .env.local file during build.
3. Note how the application loads correctly once deployed.
4. Remove the comments in the layout file to add the reading of cookies, and redeploy.
5. Note how the app fails to load due to a server error, which is the reading of an env var.

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @SamKomesarook 👋 , thanks for raising this with us!

First of all, thanks for sharing the detailed insights about the issue and also for sharing your test repository.

I was able to fork the test repository and reproduce the behavior on my end. After reading the cookies, in the `layout.tsx` file the environment variable is returned as `undefined` because the `ADMIN_TEST` variable is not made available to the server side compute runtime.

To make it accessible to the compute runtime, you will need to write environment variables to the `.env.production` file before the application build runs. Amplify Hosting will then allow your application to access these variables when the application receives traffic.

Your build specification file (amplify.yml) should look something like this:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - env | grep -e ADMIN_TEST >> .env.production
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

Here is our documentation in regards to this feature: https://docs.aws.amazon.com/amplify/latest/userguide/ssr-environment-variables.html

**Comment by SamKomesarook** [comment]
This fixed the issue, thank you!
