### ISSUE TITLE
Next.js 13 Amplify - CustomerError: The size of the build output exceeds the max allowed size of 230686720 bytes

### ISSUE THREAD

**Issue by karloespiritu** [aws-amplify/amplify-hosting#3647]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2moft81gtdgs7

### Region

us-west-2

### Environment name

Frontend builds

### If applicable, what version of Node.js are you using?

18.13

### What operating system are you using?

Mac

### Browser type?

Chrome

### Describe the bug

`CustomerError: The size of the build output (264015647) exceeds the max allowed size of 230686720 bytes. Please reduce the size of your build output and try again.`

I'm aware that Amplify has a limit of 200MB build output size for Next.js 12 and 13 apps. But our application is big and the 200MB limit is just too small for any large application. Many large-scale apps built with Next.js exceed the 200MB build output as demonstrated by other users who reported the same issue.

We already followed the build step command in the Amplify docs on how to reduce the build output size, but the size reduction is not enough to reduce the build output to less than 200MB.

`du -h -d1 public`:

 12K	        public/js
128K	public/favicon
3.2M	public/img
 48K	public/sounds
120K	public/json
4.0K	public/maintenance
3.6M	public

`du -h -d1 .next/static`:

636K	.next/static/css
 12M	.next/static/chunks
 28K	.next/static/puGf1Ftyu3ImEPqhcvPhF
264K	.next/static/media
 13M	.next/static
 
`du -h -d1 .next/server`:

5.1M	.next/server/chunks
62M 	.next/server/pages
67M	         .next/server

 
 

### Expected behavior

Build runs successfully.

### Reproduction steps

Run build, then await for build to complete.

### Additional information

![Screenshot 2023-08-15 at 8 02 08 PM](https://github.com/aws-amplify/amplify-studio/assets/219083/7d233857-976c-4bf3-98a1-00438287a133)

**Comment by Jay2113** [comment]
Hi @karloespiritu 👋 , thanks for sharing the detailed information about the issue you are experiencing while deploying your Next.js application using Amplify Hosting.

Unfortunately, the 200 MB build output size is a hard limitation at the moment. Generally, our recommendation to reduce the build output size is as follows:
- Build app using the esbuild JS bundler: https://docs.aws.amazon.com/amplify/latest/userguide/troubleshooting-ssr-deployment.html#build-output-too-large
- Store and serve your image and video files from Amazon S3 instead of the `public` directory.

Based on the size of the files in your `.next/server` directory, it seems that your Next.js application has a large amount of pages and thus it is resulting in this deployment error. A potential workaround that you can consider is to use [dynamic routes](https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes) within your Next.js application as it will reduce the overall number of pages and in turn the build output size.

**Comment by pachoclo** [comment]
+1 
Having the same issue on a relatively small project after adding Sentry.

**Comment by victorccccc** [comment]
Hi 👋, we recently made the improvement and resolved this issue, please rebuild your application. Feel free to open the new issue if it persists. Thanks

**Comment by pachoclo** [comment]
> Hi 👋, we recently made the improvement and resolved this issue, please rebuild your application. Feel free to open the new issue if it persists. Thanks

@victorccccc Could you confirm when the improvement was made and what the improvement is? We saw this limit just last week.

**Comment by mauerbac** [comment]
hi @pachoclo - this improvement was pushed out today. The team added logic to remove unnecessary packages for production that are typically large. Can you give it another try and let us know?
