### ISSUE TITLE
Annoying CustomerError: Framework Web not supported

### ISSUE THREAD

**Issue by ArianHamdi** [aws-amplify/amplify-hosting#3649]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d3akk1nl18rszx

### AWS Region

us-east-1

### Amplify Hosting feature

Build settings

### Frontend framework

Next.js

### Next.js version

13.4.8

### Next.js router

Pages Router

### Describe the bug

We get ```CustomerError: Framework Web not supported``` error every time we deploy a new branch. the framework is specefied on amplify app and it is Next.js - SSR so it is so annoying to set it for each new branches.

Always we need to run ```aws amplify update-branch --app-id <value> --branch-name <value> --framework 'Next.js - SSR'``` for each new branch. I am not looking for a hot fix to this problem and instead I want a robust way to get rid of this tedious work.

### Expected behavior

Build settings must follow amplify app settings for all branches.

### Reproduction steps

1. Create a Next.js - SSR App
2. Try to deploy a new branch
3. get  `CustomerError: Framework Web not supported` error

### Log output

<details>

```
2023-08-15T12:44:09.238Z [INFO]: # Completed phase: build
2023-08-15T12:44:09.240Z [INFO]: ## Build completed successfully
2023-08-15T12:44:09.241Z [INFO]: # Starting caching...
2023-08-15T12:44:09.247Z [INFO]: # Creating cache artifact...
2023-08-15T12:44:22.474Z [INFO]: # Created cache artifact
2023-08-15T12:44:22.562Z [INFO]: # Uploading cache artifact...
2023-08-15T12:44:27.340Z [INFO]: # Uploaded cache artifact
2023-08-15T12:44:27.451Z [INFO]: # Caching completed
2023-08-15T12:44:27.458Z [INFO]: # No custom headers found.
2023-08-15T12:44:27.461Z [ERROR]: !!! CustomerError: Framework Web not supported
2023-08-15T12:44:27.463Z [INFO]: # Starting environment caching...
2023-08-15T12:44:27.463Z [INFO]: # Environment caching completed


```

</details>

### Additional information

I found 4 related issues and all of them are closed without any acceptable solution so hopefully this one isn't like the others.

**Comment by vafPER** [comment]
This issue takes a lot of time from us, Also i think we are paying double for build times. One for the failed build and one for the build after running the command.

**Comment by ArianHamdi** [comment]
Hi guys, 
It seems this issue has been resolved.
Can someone verify if this Amplify bug was genuinely fixed and not just a random occurrence?

**Comment by Jay2113** [comment]
Hi @ArianHamdi @vafPER  👋 , thanks for raising this with us and sorry to hear that you are experiencing this issue.

From the information provided, it seems that your branch's framework attribute gets changed from `Next.js - SSR` to `Web` when you deploy a new branch on the app and on subsequent deploys the builds fail due to an incorrect framework. To mitigate this behavior, you need to first update the branch framework back to `Next.js - SSR` and then deploy it. Can you please confirm if my understanding is correct?

Additionally, can you please share some information on the new branches? Are they Next.js SSR branches or are they intended to be Next.js SSG branches? Do you also have a build specification file (amplify.yml) present at the root of your repository for each branch?

**Comment by vafPER** [comment]
@Jay2113 ,  Next js SSR branches , We don don't have build specification file  (amplify.yml) ,  We needed to first update the branch framework back to Next.js - SSR and then *RE-deploy* it after the the first deploy was failed.

As @ArianHamdi  mentioned we had a the issue for almost two months, and now it's resolved after we created this issue. 

That's why @ArianHamdi   was wondering if this Amplify bug was genuinely fixed now or it is just a random occurrence that might happen again

**Comment by Jay2113** [comment]
Thanks for sharing that context @vafPER.

Can you confirm if this behavior was observed on the following workflow/events?
- Create a Next.js SSR app and deploy it on Amplify Hosting:
  - Platform: Web_Compute
  - Framework: Next.js - SSR
- Create a new git branch (also intended to be SSR) and deploy it on the Amplify app
- The initial frontend build on this new branch fails with `CustomerError: Framework Web not supported` as the framework was detected as `Web` instead of `Next.js - SSR`
- Run the `update-branch` command to modify the branch framework
- Builds are now deployed successfully

If yes, in that case can you also confirm if your new branch's `package.json` file is configured as SSR: https://docs.aws.amazon.com/amplify/latest/userguide/deploy-nextjs-app.html#package.json-settings?
