### ISSUE TITLE
Can't upgrade to web compute for nextjs 13

### ISSUE THREAD

**Issue by berniefitz82** [aws-amplify/amplify-hosting#3675]
I'm a newbie at this. I had a CRA app that I've converted to a nextjs v13 app. I can't deploy without build errors. I've read the docs that say a banner should appear for me to upgrade the environment for nextjs 13, but that banner never appears. My framework is stuck as web dynamic.

Any pointers as to forcing the framework change or avenues I should be pursuing?

**Comment by Jay2113** [comment]
Hi @berniefitz82 👋 , thanks for reaching out to us and we are sorry to hear that you are running into this issue.

We have temporarily disabled the workflow to migrate Next.js apps from `Web_Dynamic` (classic) to `Web_Compute` platform as we have identified an issue associated to it and are actively working on addressing it. We will re-enable the migration after the issue is resolved and we apologize for the inconvenience caused due to this.

In the meantime, would it be feasible for you to follow this workflow?
- Upgrade your app's Next.js version to >12 in `package.json` file
- Perform a clean install of the dependencies
  - `rm -rf node_modules`
  - `rm package-lock.json`
  - `npm install`
- Commit the changes to the git repository
- Create a new Amplify app and connect it to the same git repository 
- This should allow you to deploy the app using the `Web_Compute` platform.

**Comment by Jay2113** [comment]
@rouven Unfortunately, we don't have an ECD to share at this moment but please rest assured that we are actively working on re-enabling the migration workflow and will keep you posted with any updates.

**Comment by marlonmarcello** [comment]
We are currently going through a migration from Next 10 to 13 and we are currently stuck on this as well.  

We are getting the following error during the `Deploy` step:
```
2023-09-25T20:47:36 [INFO]: Beginning deployment for application d1wa0wwusudt8t, branch:dev, buildId 0000000608
2023-09-25T20:47:36 [INFO]: Build Artifacts not found.
2023-09-25T20:47:36 [ERROR]: {"code":"MissingBuildArtifacts"}
```
I have a feeling that it's because we can't run the migration.

@Jay2113 does the team have any updates on this?

**Comment by james-simpson-ST** [comment]
@Jay2113 is there any update or ECD that you can share? We also would like to migrate and would prefer to use the automated migration instead of working out a migration plan of our own especially as it would require a domain migration too and we have multiple apps that would need migrating.

**Comment by wimvero** [comment]
> @Jay2113 is there any update or ECD that you can share? We also would like to migrate and would prefer to use the automated migration instead of working out a migration plan of our own especially as it would require a domain migration too and we have multiple apps that would need migrating.

We're in the same boat here, hopefully we can get a status update sometime soon!

**Comment by patorpey** [comment]
Likewise. We'd probably manage creating a new app for deployment and domain migration. It's migrating our production database and user pool to the new app that gives us pause. The ability to upgrade to WEB_COMPUTE on the existing app is preferable.

An update on this issue would allow us to plan our technical and business strategy accordingly, instead of standing by on our application updates indefinitely.

**Comment by patorpey** [comment]
Likewise. We'd probably manage creating a new app for deployment and domain migration. It's migrating our production database and user pool to the new app that gives us pause. The ability to upgrade to `WEB_COMPUTE` on the existing app is preferable.

We're standing by on our application changes, so an update on this issue would allow us to plan our technical and business strategy accordingly.

**Comment by Jay2113** [comment]
Hi everyone 👋 , thank you for your continued patience and we apologize for the inconvenience caused due to this issue. We have re-enabled the workflow to migrate Next.js SSR apps from `Web_Dynamic` (classic) to the `Web_Compute` platform. You should now be able to initiate the migration of your apps from the Amplify Console. You can refer to this documentation for detailed instructions: https://docs.aws.amazon.com/amplify/latest/userguide/update-app-nextjs-version.html.
