### ISSUE TITLE
Migrating from ReactJS to NextJS and having this error:  404 Error()

### ISSUE THREAD

**Issue by ghufran2508** [aws-amplify/amplify-hosting#3681]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1plugrqiuk4q4

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments, Frontend builds, Git providers

### Question

I had a project on github and it was deployed to AWS Amplify built in Reactjs, Then I decided to migrate from Reactjs to Nextjs. I made new project and after making all the changes, I pushed and replaced all the changes in that repository, it deployed on AWS successfully, but it doesn't showing anything on the given domain link by Amplify and getting this error: Failed to load resource: the server responded with a status of 404 ().
Is it a good approach to migrat ReactJS project to NextJS and deploy in the same instance in AWS Amplify?

**Comment by Jay2113** [comment]
Hi @ghufran2508 👋 , thanks for raising this!

It seems that your `production` branch is resolving as expected (both the .amplifyapp.com subdomain and custom domain). The outlined behavior is typically caused due to an incorrect [`baseDirectory`](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#yml-specification-syntax) field within the build specification file (amplify.yml). Thus, I'd recommend reviewing the same.
