### ISSUE TITLE
ls: cannot access ./.next/standalone/**/*.js: No such file or directory

### ISSUE THREAD

**Issue by vishalobrizum** [aws-amplify/amplify-hosting#3682]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2q7cj32******

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Frontend framework

Next.js

### Next.js version

13

### Next.js router

App Router

### Describe the bug

Context: I ran into 200 MB hard limit build error. 

Upon following this article (https://docs.aws.amazon.com/amplify/latest/userguide/troubleshooting-ssr-deployment.html#) and changing my build, now I am getting this error:

ls: cannot access ./.next/standalone/**/*.js: No such file or directory

### Expected behavior

I am not able to deploy my app. Its frustrating

### Reproduction steps

1. Create a heavy (lots of deps) nextjs v13 application.. It should be enough such that it causes 200MB Amplify size limit error 
2. Deploy to amplify

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Jay2113** [comment]
Hi @vishalobrizum 👋  , thanks for raising this!

To give you some context, previously our app bundling strategy relied on the Next.js standalone mode. Since then we have made improvements to how we bundle Next.js apps and are no longer relying on the standalone mode.

Unfortunately, the 200 MB build output size is a hard limitation at the moment. Can you check what is taking the most of the size of your build output?
```
npm run build or yarn build -> Production build
du -h -d1 public -> Public directory
du -h -d1 .next/static -> Static files
du -h -d1 .next/server -> Next server files
```

Additionally, the troubleshooting steps in the outlined documentation seem to be outdated and we will work on updating them.
