### ISSUE TITLE
amplify push vs git push

### ISSUE THREAD

**Issue by mat-b** [aws-amplify/amplify-hosting#3716]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2kf2ltunv8xfd

### AWS Region

eu-west-1

### Amplify Hosting feature

Backend builds

### Question

I am using AWS CodeCommit as git repo for my Amplify app. 

What is the relation between "amplify push" and "git push"? When should I one and when the other?

The "backend" folder is part of the git repo, so when I change something in the backend code should I use "git push" or "amplify push"?
Should I use "amplify push" only after some "amplify add/remove" operations? and "git push" after other changes?
Should I use both of them in sequence?

**Comment by Jay2113** [comment]
Hi @mat-b 👋 , thanks for raising this!

Based on the information provided, I understand that you are trying to perform full stack deployments with Amplify Hosting. Since your `amplify` folder (backend) is part of the git repository, the best practice would be to use `git push` after modifying the backend code. This should then trigger the CI/CD pipeline in the Amplify Console and a new build will start.

Similarly, if you wish to add/remove categories to the existing backend, you can do so using the Amplify CLI via `amplify add/remove category`. To continue with full stack deployments, you will then need to use `git push` to send your local changes to the remote git repository instead of performing `amplify push` using the Amplify CLI.
