### ISSUE TITLE
Unauthorized automatic build and deployment - project building on every push even though build is DISABLED for the branch

### ISSUE THREAD

**Issue by naedx** [aws-amplify/amplify-hosting#3740]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

N/A

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Frontend framework

Angular

### Next.js version

N/A

### Next.js router

N/A

### Describe the bug

My project was configured for automatic builds on each push to the branch. I have since disabled that but I see that the backend is still being deployed in the background. 

This is likely related to my earlier issue here ( ⁠Arbitrarily failing CI/CD: "Dep… ) where a deliberately configured build would fail with message "deployment is already in progress". Since this happens on every push to my branch.

I'm probably paying for all these unintentional builds, as well as the failed ones due to the problem. But more importantly, it breaks my project because the builds seem to ignore my amplify.yml build script and so parts of the project are deployed incorrectly. 

Further information:

These unintentional builds do not show up in the Amplify (Web) Console under "Build History".
The unintentional builds show up under Backend > Overview > "Last deployment activity"

### Expected behavior

1. The build should only execute iff I've enabled automatic builds for that branch. 
2. The build should appear in build history.

### Reproduction steps

I don't know if it's possible to write steps to get this to happen because this hasn't happened with other project or even other environments in the same project. However, for me reproducing this issue is as follows:

1. git push 

### Additional information

![amplify](https://github.com/aws-amplify/amplify-hosting/assets/1711099/1956fc54-8b89-45cf-845e-04eb8685e7d6)

**Comment by naedx** [comment]
This is a duplicate of the issue that was posted in amplify-help on discord (Sept 8, 2023): https://discord.com/channels/705853757799399426/1149680933755179079/1149680933755179079

**Comment by Jay2113** [comment]
Hi @naedx 👋 , thanks for raising this and for sharing detailed information on the issue that you are experiencing.

I was unable to reproduce this behavior when performing the following steps:
- Create a sample react app using `npx create-react-app`
- Initialize a new amplify backend using `amplify init` -> This will create a new Amplify app in the Amplify Console
- Add a sample `authentication` category to the backend using `amplify add auth`
- Push the changes to the cloud using `amplify push`
- Commit and push the changes to the git repository via `git push`
- Connect the frontend to the existing Amplify app in the Amplify Console 
   - Enable full-stack deployments
   - Select existing backend environment (as stated in Step 2)
   - Select backend service IAM role
- Save and deploy
- The CI/CD pipeline kicks off and it will perform both the backend and frontend builds and once deployed the Amplify URL will render the React website.
- From the Amplify Console, disable `auto-build` feature on the branch
- Create a minor change to the UI and add a `storage` category to the backend using `amplify add storage` -> I did not perform an `amplify push` just staged it locally on the git branch.
- Commit and push the changes to the remote git repository via `git push`
- Result: No frontend and/or backend build was triggered. I also confirmed that no updates were made to the underlying CloudFormation stack via the deployment activity tab in the Amplify Console

Since you are observing changes in the deployment activity backend tab in the Amplify Console, its possible that the changes could be due to the backend being shared maybe with a different Amplify app: https://docs.aws.amazon.com/amplify/latest/userguide/reuse-backends.html . An additional thing that you can check is the actual changes that are being made to the amplify backend's underlying CloudFormation stack.

**Comment by naedx** [comment]
Hi @Jay2113 , thank you for your reply. As per your suggestion, I searched and found that there was another project that was connected to the repo which was triggering the build! This completely resolves my issue. No more hair pulling :)

Thank you!
