### ISSUE TITLE
Domain activation issue 

### ISSUE THREAD

**Issue by Nazmul19285** [aws-amplify/amplify-hosting#3832]
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1srta09l28lic

### Region

us-east-1

### Step

Domain activation

### Status

Failed

### Issue or question

![image](https://github.com/aws-amplify/amplify-hosting/assets/60980415/e8b682cc-4543-4cb7-b6dd-d72ef1664d5d)

I'm trying to connect my domain but this is happening every time. Please, help me to solve this issue.

### Error message

One or more of the CNAMEs you provided are already associated with a different resource.

**Comment by yocoso** [comment]
hello i was facing the same issue and just got it resolved.
I found the I make a mistake in adding the CNAME for enable the https. 
there is an ending period on the name and I missed that. After I fixed it, my domain turns to available very soon but now facing new problem.
I am not sure if you are caused by the same reason but worth a double check.

**Comment by ClaudioAleksitchKVMT** [comment]
I have the same problem. the problem is not with the CNAME certificate. It's probably with Cloudfront's CNAME. I deleted my custom domain to try to create it with a custom certificate in ACM, but it didn't work and after that I started having this error

**Comment by Jay2113** [comment]
Hi @Nazmul19285 👋 , thanks for reaching out. I observed that your Amplify app `d1srta09l28lic` has been deleted.

If the issue persists or resurfaces, I'll recommend reviewing our custom domain troubleshooting guide which outlines the root cause of the `CNAMEAlreadyExistsException` error and steps to mitigate it: https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html#i-get-a-cnamealreadyexistsexception-error.
